#ifdef VERSION_GCCJGC
extern "C" {
const char s_menuEmptyJp[] = "";
const char s_menuYesJp[] = "\x82\xCD\x82\xA2";
const char s_menuNoJp[] = "\x82\xA2\x82\xA2\x82\xA6";
const char s_menuCancelJp[] = "\x82\xC6\x82\xE8\x82\xAF\x82\xB5";
const char s_menuGilJp[] = "\x83\x4D\x83\x8B";
const char s_menuStrengthJp[] = "\x82\xB1\x82\xA4\x82\xB0\x82\xAB";
const char s_menuDefenceJp[] = "\x82\xDA\x82\xA4\x82\xAC\x82\xE5";
const char s_menuMagicJp[] = "\x82\xDC\x82\xD9\x82\xA4";
const char s_menuMemoriesJp[] = "\x8E\x76\x82\xA2\x8F\x6F\x82\xCC\x90\x94";
const char s_menuAttackJp[] = "\x82\xBD\x82\xBD\x82\xA9\x82\xA4";
const char s_menuDefendJp[] = "\x82\xDC\x82\xE0\x82\xE9";
const char s_menuRemoveJp[] = "\x82\xCD\x82\xB8\x82\xB7";
const char s_menuFuseJp[] = "\x82\xAA\x82\xC1\x82\xBD\x82\xA2";
const char s_menuSplitJp[] = "\x82\xA9\x82\xA2\x82\xB6\x82\xE5";
const char s_menuUseJp[] = "\x82\xC2\x82\xA9\x82\xA4";
const char s_menuDropJp[] = "\x82\xA8\x82\xAD";
const char s_menuDestroyJp[] = "\x82\xB1\x82\xED\x82\xB7";
const char s_menuMaleJp[] = "\x82\xA8\x82\xC6\x82\xB1";
const char s_menuFemaleJp[] = "\x82\xA8\x82\xF1\x82\xC8";
const char s_menuAllJp[] = "\x82\xBA\x82\xF1\x82\xA2\x82\xF1";
const char s_menuUnknownJp[] = "\x81\x48\x81\x48\x81\x48";
const char s_menuFatherJp[] = "\x82\xBF\x82\xBF";
const char s_menuMotherJp[] = "\x82\xCD\x82\xCD";
const char s_menuOlderBrotherJp[] = "\x82\xA0\x82\xC9";
const char s_menuOlderSisterJp[] = "\x82\xA0\x82\xCB";
const char s_menuYoungerBrotherJp[] = "\x82\xA8\x82\xC6\x82\xA4\x82\xC6";
const char s_menuYoungerSisterJp[] = "\x82\xA2\x82\xE0\x82\xA4\x82\xC6";
const char s_menuSpouseJp[] = "\x82\xCD\x82\xA2\x82\xAE\x82\xA4\x82\xB5\x82\xE1";
const char s_menuLettersJp[] = "\x82\xC4\x82\xAA\x82\xDD\x82\xA2\x82\xBF\x82\xE7\x82\xF1";
const char s_menuSendItemJp[] = "\x83\x41\x83\x43\x83\x65\x83\x80\x82\xF0\x82\xC2\x82\xAF\x82\xE9";
const char s_menuSendGilJp[] = "\x83\x4D\x83\x8B\x82\xF0\x82\xC2\x82\xAF\x82\xE9";
const char s_menuSendNothingJp[] = "\x82\xC8\x82\xC9\x82\xE0\x82\xC2\x82\xAF\x82\xC8\x82\xA2";
const char s_menuProceedJp[] = "\x82\xB1\x82\xEA\x82\xC5\x82\xE6\x82\xEB\x82\xB5\x82\xA2\x82\xC5\x82\xB7\x82\xA9\x81\x48";
const char s_menuTakeOutJp[] = "\x82\xF0\x82\xC6\x82\xE8\x82\xBE\x82\xB5\x82\xDC\x82\xB7\x82\xA9\x81\x48";
const char s_menuOpenQuoteJp[] = "\x81\x77";
const char s_menuCloseQuoteJp[] = "\x81\x78";
const char s_menuSendJp[] = "\x82\xC6\x82\xA8\x82\xAD\x82\xE9";
const char s_menuReplyToJp[] = "\x82\xC9";
const char s_menuSendReplyJp[] = "\x82\xC6\x82\xA8\x82\xAD\x82\xE8\x82\xDC\x82\xB7";
const char s_menuIncludeJp[] = "\x82\xF0\x82\xC2\x82\xAF\x82\xDC\x82\xB7";
const char s_menuConfirmJp[] = "\x8C\x88\x92\xE8";
const char s_menuNameJp[] = "\x96\xBC\x91\x4F";
const char s_menuGenderJp[] = "\x90\xAB\x95\xCA";
const char s_menuTribeJp[] = "\x8E\xED\x91\xB0";
const char s_menuFamilyTradeJp[] = "\x90\x65\x82\xCC\x90\x45\x8B\xC6";
const char s_menuCommandListJp[] = "\x83\x52\x83\x7D\x83\x93\x83\x68\x83\x8A\x83\x58\x83\x67";
const char s_menuItemsJp[] = "\x83\x41\x83\x43\x83\x65\x83\x80";
const char s_menuEquipJp[] = "\x82\xBB\x82\xA4\x82\xD1";
const char s_menuArtifactsJp[] = "\x83\x41\x81\x5B\x83\x65\x83\x42\x83\x74\x83\x40\x83\x4E\x83\x67";
const char s_menuTreasuresJp[] = "\x82\xA0\x82\xB8\x82\xA9\x82\xE8\x82\xE0\x82\xCC";
const char s_menuMoneyJp[] = "\x82\xA8\x82\xA9\x82\xCB";
const char s_menuFavoritesJp[] = "\x82\xB1\x82\xA4\x82\xD4\x82\xC2";
const char s_menuFamilyJp[] = "\x82\xA9\x82\xBC\x82\xAD";
const char s_menuLetterJp[] = "\x82\xC4\x82\xAA\x82\xDD";
const char s_menuDoneJp[] = "\x82\xBB\x82\xCC\x82\xDC\x82\xDC";
const char* gSingMenuTextTableJp[56] = {
    s_menuEmptyJp, s_menuYesJp, s_menuNoJp, s_menuCancelJp,
    s_menuGilJp, s_menuStrengthJp, s_menuDefenceJp, s_menuMagicJp,
    s_menuMemoriesJp, s_menuAttackJp, s_menuDefendJp, s_menuRemoveJp,
    s_menuFuseJp, s_menuSplitJp, s_menuUseJp, s_menuDropJp,
    s_menuDestroyJp, s_menuMaleJp, s_menuFemaleJp, s_menuAllJp,
    s_menuUnknownJp, s_menuGilJp, s_menuFatherJp, s_menuMotherJp,
    s_menuOlderBrotherJp, s_menuOlderSisterJp, s_menuYoungerBrotherJp, s_menuYoungerSisterJp,
    s_menuSpouseJp, s_menuLettersJp, s_menuSendItemJp, s_menuSendGilJp,
    s_menuSendNothingJp, s_menuProceedJp, s_menuTakeOutJp, s_menuOpenQuoteJp,
    s_menuCloseQuoteJp, s_menuSendJp, s_menuReplyToJp, s_menuSendReplyJp,
    s_menuIncludeJp, s_menuConfirmJp, s_menuNameJp, s_menuGenderJp,
    s_menuTribeJp, s_menuFamilyTradeJp, s_menuCommandListJp, s_menuItemsJp,
    s_menuEquipJp, s_menuArtifactsJp, s_menuTreasuresJp, s_menuMoneyJp,
    s_menuFavoritesJp, s_menuFamilyJp, s_menuLetterJp, s_menuDoneJp,
};
}
#endif
