#ifndef _FFCC_REDSOUND_REDEXECUTE_H
#define _FFCC_REDSOUND_REDEXECUTE_H

#include <dolphin/ax.h>
#include "types.h"

class AXFX_BUFFERUPDATE;
struct RedTrackDATA;
struct RedSoundCONTROL;
struct RedKeyOnDATA;

struct RedReverbDATA {
	int callback;
	void* context;
	int kind;
};

enum RedReverbKind {
	REDSOUND_REVERB_KIND_NONE = 0,
	REDSOUND_REVERB_KIND_STD = 1,
	REDSOUND_REVERB_KIND_HI = 2,
	REDSOUND_REVERB_KIND_DELAY = 3,
	REDSOUND_REVERB_KIND_CHORUS = 4,
	REDSOUND_REVERB_KIND_HI_DPL2 = 5,
};

struct RedReverbSize {
	u32 m_requested;
	u32 m_aligned;
};

struct RedNoteDATA {
	signed char m_key;
	signed char m_velocity;
	unsigned char m_allocFlags;
	unsigned char m_pad03;
};

enum RedNoteAllocFlag {
	REDSOUND_NOTE_ALLOC_DIRECT = 1,
	REDSOUND_NOTE_ALLOC_STREAM = 2,
	REDSOUND_NOTE_ALLOC_RESERVED = 4,
	REDSOUND_NOTE_ALLOC_PRIORITY = 8,
	REDSOUND_NOTE_ALLOC_DIRECT_MASK = REDSOUND_NOTE_ALLOC_DIRECT | REDSOUND_NOTE_ALLOC_RESERVED,
};

struct RedWaveDATA {
	unsigned int m_flags;
	int m_sampleStart;
	int m_loopStart;
	int m_loopEnd;
	unsigned char m_pad10[0x14 - 0x10];
	int m_pitch;
	signed char m_splitKey;
	unsigned char m_splitVelocity;
	unsigned char m_volume;
	unsigned char m_pan;
	signed char m_reverbMix;
	unsigned char m_pad1D[0x22 - 0x1D];
	unsigned char m_adpcmData[0x4A - 0x22];
	unsigned char m_adpcmLoop[0x50 - 0x4A];
	unsigned char m_adsr[0x5C - 0x50];
	unsigned char m_pad5C[0x60 - 0x5C];
};

enum RedWaveFlag {
	REDSOUND_WAVE_FLAG_PAIRED_ENTRY = 1,
	REDSOUND_WAVE_FLAG_SPLIT_END = 0x200,
	REDSOUND_WAVE_FLAG_SPLIT_TABLE = 0x30000,
	REDSOUND_WAVE_FLAG_USE_WAVE_KEY = 0x20000,
};

enum RedWaveLayoutOffset {
	REDSOUND_WAVE_REVERB_MIX_OFFSET = 0x1C,
};

struct RedVoiceDATA {
	RedTrackDATA* m_track;
	RedWaveDATA* m_waveData;
	int* m_trackVolume;
	int* m_trackExpression;
	int* m_trackPan;
	AXVPB* m_axVoice;
	signed char m_key;
	signed char m_velocity;
	unsigned char m_stateFlags;
	unsigned char m_notePad;
	int m_pitchModPhase;
	int m_pitchModFrames;
	int m_pitchModFrame;
	short m_pitchModDelay;
	unsigned char m_pad2A[0x2C - 0x2A];
	int m_volumeModPhase;
	int m_volumeModFrames;
	int m_volumeModFrame;
	short m_volumeModDelay;
	unsigned char m_pad3A[0x3C - 0x3A];
	int m_randomPitch;
	int m_randomVolume;
	int m_randomPan;
	unsigned char m_pad48[0x50 - 0x48];
	unsigned short m_adsrTime[4];
	unsigned char m_adsrLevel[4];
	int m_adsrStage;
	int m_adsrStepFrames;
	int m_adsrStepAdd;
	unsigned short m_axMix[0x12];
	int m_active;
	unsigned int m_flags;
	unsigned int m_voiceSwitch;
	int m_pitch;
	int m_targetPitch;
	int m_basePitch;
	unsigned char m_padA4[0xA8 - 0xA4];
	int m_voiceIndex;
	int m_adsrCurrentLevel;
	int m_envelopeLevel;
	unsigned char m_padB4[0xB8 - 0xB4];
	unsigned int m_updateFlags;
	unsigned char m_padBC[0xC0 - 0xBC];
};

enum RedVoiceAdsrLayout {
	REDSOUND_VOICE_ADSR_TIME_OFFSET = 0x50,
	REDSOUND_VOICE_ADSR_LEVEL_OFFSET = 0x58,
	REDSOUND_VOICE_ADSR_STAGE_OFFSET = 0x5C,
	REDSOUND_WAVE_ADSR_OFFSET = 0x50,
	REDSOUND_VOICE_ADSR_TIME_HALFWORD = REDSOUND_VOICE_ADSR_TIME_OFFSET / sizeof(u16),
	REDSOUND_VOICE_ADSR_LEVEL_BASE = 9,
	REDSOUND_VOICE_ADSR_STAGE_COUNT = 3,
};

enum RedVoiceLayoutOffset {
	REDSOUND_VOICE_TRACK_OFFSET = 0x00,
	REDSOUND_VOICE_STATE_FLAGS_OFFSET = 0x1A,
	REDSOUND_VOICE_AX_MIX_OFFSET = 0x68,
	REDSOUND_VOICE_ACTIVE_OFFSET = 0x8C,
	REDSOUND_VOICE_FLAGS_OFFSET = 0x90,
	REDSOUND_VOICE_SWITCH_OFFSET = 0x94,
	REDSOUND_VOICE_INDEX_OFFSET = 0xA8,
	REDSOUND_VOICE_AX_MIX_SIZE = 0x24,
};

enum RedVoiceLayoutWord {
	REDSOUND_VOICE_TRACK_WORD = REDSOUND_VOICE_TRACK_OFFSET / sizeof(u32),
	REDSOUND_VOICE_WAVE_DATA_WORD = 1,
	REDSOUND_VOICE_TRACK_VOLUME_WORD = 2,
	REDSOUND_VOICE_TRACK_EXPRESSION_WORD = 3,
	REDSOUND_VOICE_TRACK_PAN_WORD = 4,
	REDSOUND_VOICE_NOTE_WORD = 6,
	REDSOUND_VOICE_RANDOM_PITCH_WORD = 0x0F,
	REDSOUND_VOICE_RANDOM_VOLUME_WORD = 0x10,
	REDSOUND_VOICE_RANDOM_PAN_WORD = 0x11,
	REDSOUND_VOICE_AX_MIX_WORD = REDSOUND_VOICE_AX_MIX_OFFSET / sizeof(u32),
	REDSOUND_VOICE_ACTIVE_WORD = REDSOUND_VOICE_ACTIVE_OFFSET / sizeof(u32),
	REDSOUND_VOICE_FLAGS_WORD = REDSOUND_VOICE_FLAGS_OFFSET / sizeof(u32),
	REDSOUND_VOICE_SWITCH_WORD = REDSOUND_VOICE_SWITCH_OFFSET / sizeof(u32),
	REDSOUND_VOICE_INDEX_WORD = REDSOUND_VOICE_INDEX_OFFSET / sizeof(u32),
	REDSOUND_VOICE_INDEX_MASK = 0x1F,
	REDSOUND_VOICE_ADSR_TIME_WORD = REDSOUND_VOICE_ADSR_TIME_OFFSET / sizeof(u32),
	REDSOUND_VOICE_TARGET_PITCH_WORD = 0x26,
	REDSOUND_VOICE_BASE_PITCH_WORD = 0x28,
	REDSOUND_VOICE_ADSR_CURRENT_WORD = 0x2B,
	REDSOUND_VOICE_ENVELOPE_WORD = 0x2C,
	REDSOUND_VOICE_UPDATE_FLAGS_WORD = 0x2E,
};

enum RedRandomByteLayout {
	REDSOUND_RANDOM_BYTE_MASK = 0xFF,
	REDSOUND_RANDOM_BYTE_SIGN_BIT = 0x80,
};

enum RedVoiceCleanupMask {
	REDSOUND_VOICE_STATE_PLAYING = 1,
	REDSOUND_VOICE_STATE_STREAM = 2,
	REDSOUND_VOICE_STATE_SE = 4,
	REDSOUND_VOICE_STATE_PLAYING_MASK = REDSOUND_VOICE_STATE_PLAYING | REDSOUND_VOICE_STATE_STREAM,
	REDSOUND_VOICE_STATE_ANY_MASK =
	    REDSOUND_VOICE_STATE_PLAYING | REDSOUND_VOICE_STATE_STREAM | REDSOUND_VOICE_STATE_SE,
	REDSOUND_VOICE_STATE_CLEAR_STREAM_MASK = ~REDSOUND_VOICE_STATE_STREAM,
	REDSOUND_VOICE_STATE_CLEAR_PLAYING_MASK = -6,
	REDSOUND_VOICE_SWITCH_LOOP = 1,
	REDSOUND_VOICE_SWITCH_REVERB_AUX_A = 2,
	REDSOUND_VOICE_SWITCH_SUSTAIN = 4,
	REDSOUND_VOICE_SWITCH_PAUSE = 8,
	REDSOUND_VOICE_SWITCH_PAIRED_LEFT = 0x40,
	REDSOUND_VOICE_SWITCH_PAIRED_RIGHT = 0x80,
	REDSOUND_VOICE_SWITCH_PAIRED_PAN = REDSOUND_VOICE_SWITCH_PAIRED_LEFT | REDSOUND_VOICE_SWITCH_PAIRED_RIGHT,
	REDSOUND_VOICE_SWITCH_DRY_LEFT = 0x400,
	REDSOUND_VOICE_SWITCH_DRY_RIGHT = 0x800,
	REDSOUND_VOICE_SWITCH_DRY_STEREO = REDSOUND_VOICE_SWITCH_DRY_LEFT | REDSOUND_VOICE_SWITCH_DRY_RIGHT,
	REDSOUND_VOICE_SWITCH_REVERB_LEFT = 0x1000,
	REDSOUND_VOICE_SWITCH_REVERB_RIGHT = 0x2000,
	REDSOUND_VOICE_SWITCH_REVERB_STEREO = REDSOUND_VOICE_SWITCH_REVERB_LEFT | REDSOUND_VOICE_SWITCH_REVERB_RIGHT,
	REDSOUND_VOICE_SWITCH_MIX_ALL = REDSOUND_VOICE_SWITCH_DRY_STEREO | REDSOUND_VOICE_SWITCH_REVERB_STEREO,
	REDSOUND_VOICE_SWITCH_FUZZY_PITCH = 0x4000,
	REDSOUND_VOICE_SWITCH_FUZZY_VOLUME = 0x8000,
	REDSOUND_VOICE_SWITCH_FUZZY_PAN = 0x10000,
	REDSOUND_VOICE_SWITCH_FUZZY_DELTA_TIME = 0x20000,
	REDSOUND_VOICE_SWITCH_FUZZY_ADSR = 0x40000,
	REDSOUND_VOICE_SWITCH_CLEAR_PAUSE_MASK = ~REDSOUND_VOICE_SWITCH_PAUSE,
	REDSOUND_VOICE_SWITCH_CLEAR_SUSTAIN_PAUSE_MASK = ~(REDSOUND_VOICE_SWITCH_SUSTAIN | REDSOUND_VOICE_SWITCH_PAUSE),
	REDSOUND_VOICE_SWITCH_CLEAR_REVERB_MASK = ~REDSOUND_VOICE_SWITCH_REVERB_STEREO,
	REDSOUND_VOICE_SWITCH_CLEAR_MIX_MASK = ~REDSOUND_VOICE_SWITCH_MIX_ALL,
	REDSOUND_VOICE_SWITCH_CLEAR_SE_MASK = 0xfffffff7,
	REDSOUND_VOICE_FLAGS_START = 1,
	REDSOUND_VOICE_FLAGS_CLEAR_ACTIVE_MASK = 0xfffffffe,
	REDSOUND_VOICE_FLAGS_RELEASED = 2,
	REDSOUND_VOICE_FLAGS_RELEASE_ACTIVE = 4,
	REDSOUND_VOICE_FLAGS_CLEAR_RELEASE_ACTIVE_MASK = ~REDSOUND_VOICE_FLAGS_RELEASE_ACTIVE,
	REDSOUND_VOICE_FLAGS_ADPCM_DIRTY = 8,
	REDSOUND_VOICE_FLAGS_PITCH_DIRTY = 0x10,
	REDSOUND_VOICE_FLAGS_ADSR_START = 0x20,
	REDSOUND_VOICE_FLAGS_ADSR_DIRTY = 0x3C0,
	REDSOUND_VOICE_FLAGS_PAUSE_DIRTY = REDSOUND_VOICE_FLAGS_ADPCM_DIRTY | REDSOUND_VOICE_FLAGS_PITCH_DIRTY,
	REDSOUND_VOICE_FLAGS_STREAM_START =
	    REDSOUND_VOICE_FLAGS_START | REDSOUND_VOICE_FLAGS_ADPCM_DIRTY | REDSOUND_VOICE_FLAGS_PITCH_DIRTY,
	REDSOUND_VOICE_FLAGS_EXECUTE_KEEP_MASK = 0xFFFFFC24,
};

enum RedVoiceUpdateFlag {
	REDSOUND_VOICE_UPDATE_PITCH = 1,
	REDSOUND_VOICE_UPDATE_VOLUME = 2,
	REDSOUND_VOICE_UPDATE_ALL = REDSOUND_VOICE_UPDATE_PITCH | REDSOUND_VOICE_UPDATE_VOLUME,
};

u8 GetRandomData();
int PitchCompute(int, int, int, int);
void* ReverbAreaAlloc(unsigned long);
void ReverbAreaFree(void*);
void InitReverb();
int* SetReverb(int, int, int*);

RedVoiceDATA* EntryVoiceSearch(RedTrackDATA*);
void SetVoiceVolumeMix(RedVoiceDATA*, int, int);
void SetVoiceAccess(RedTrackDATA*, int);
void SetVoiceSwitch(RedTrackDATA*, int);

void EnvelopeKeyExecute();

void MusicSkipFunction();

void MainControl(int);

#endif // _FFCC_REDSOUND_REDEXECUTE_H
