#ifndef FFCC_REDSOUND_REDGLOBALS_H
#define FFCC_REDSOUND_REDGLOBALS_H

#include "PowerPC_EABI_Support/Msl/MSL_C/MSL_Common/file_io.h"
#include "dolphin/os.h"
#include "ffcc/RedSound/RedEntry.h"
#include "ffcc/RedSound/RedMidiCtrl.h"
#include "ffcc/RedSound/RedStream.h"
#include "types.h"

class CRedDriver;
class CRedEntry;
class CRedMemory;

struct RedControlRamp {
	int m_value;
	int m_step;
	int m_count;
};

enum RedControlRampLayout {
	REDSOUND_CONTROL_RAMP_VALUE_OFFSET = (unsigned int)&(((RedControlRamp*)0)->m_value),
	REDSOUND_CONTROL_RAMP_STEP_OFFSET = (unsigned int)&(((RedControlRamp*)0)->m_step),
	REDSOUND_CONTROL_RAMP_COUNT_OFFSET = (unsigned int)&(((RedControlRamp*)0)->m_count),
	REDSOUND_CONTROL_RAMP_SIZE = sizeof(RedControlRamp),
};

struct RedReverbDepth {
	int m_depth;
	int m_step;
	int m_count;
};

enum RedReverbDepthLayout {
	REDSOUND_REVERB_DEPTH_DEPTH_OFFSET = (unsigned int)&(((RedReverbDepth*)0)->m_depth),
	REDSOUND_REVERB_DEPTH_STEP_OFFSET = (unsigned int)&(((RedReverbDepth*)0)->m_step),
	REDSOUND_REVERB_DEPTH_COUNT_OFFSET = (unsigned int)&(((RedReverbDepth*)0)->m_count),
	REDSOUND_REVERB_DEPTH_SIZE = sizeof(RedReverbDepth),
};

enum RedSoundMode {
	REDSOUND_SOUND_MODE_STEREO = 0,
	REDSOUND_SOUND_MODE_MONO = 1,
	REDSOUND_SOUND_MODE_SURROUND = 2,
};

enum RedSoundControlIndex {
	REDSOUND_CONTROL_MUSIC_PRIMARY = 0,
	REDSOUND_CONTROL_MUSIC_SECONDARY = 1,
	REDSOUND_CONTROL_MUSIC_SKIP = 2,
	REDSOUND_CONTROL_SE = 3,
	REDSOUND_CONTROL_MUSIC_PLAY_END = REDSOUND_CONTROL_MUSIC_SKIP,
	REDSOUND_CONTROL_MUSIC_ALL_END = REDSOUND_CONTROL_SE,
};

enum RedSoundLayoutSize {
	REDSOUND_TRACK_SIZE = sizeof(RedTrackDATA),
	REDSOUND_CONTROL_SIZE = sizeof(RedSoundCONTROL),
	REDSOUND_CONTROL_COUNT = 4,
	REDSOUND_CONTROL_BUFFER_SIZE = REDSOUND_CONTROL_SIZE * REDSOUND_CONTROL_COUNT,
	REDSOUND_CONTROL_SECONDARY_OFFSET = REDSOUND_CONTROL_SIZE * REDSOUND_CONTROL_MUSIC_SECONDARY,
	REDSOUND_CONTROL_SKIP_OFFSET = REDSOUND_CONTROL_SIZE * REDSOUND_CONTROL_MUSIC_SKIP,
	REDSOUND_CONTROL_MASTER_VOLUME_OFFSET = (unsigned int)&(((RedSoundCONTROL*)0)->m_masterVolume),
	REDSOUND_CONTROL_MASTER_VOLUME_ADD_OFFSET = (unsigned int)&(((RedSoundCONTROL*)0)->m_masterVolumeAdd),
	REDSOUND_CONTROL_MASTER_VOLUME_DELTA_OFFSET = (unsigned int)&(((RedSoundCONTROL*)0)->m_masterVolumeDelta),
	REDSOUND_CONTROL_MUSIC_ID_OFFSET = (unsigned int)&(((RedSoundCONTROL*)0)->m_musicId),
	REDSOUND_SE_TRACK_COUNT = 0x20,
	REDSOUND_SE_TRACK_LAST_INDEX = REDSOUND_SE_TRACK_COUNT - 1,
	REDSOUND_SE_TRACK_ARENA_SIZE = REDSOUND_TRACK_SIZE * REDSOUND_SE_TRACK_COUNT,
	REDSOUND_SE_VOICE_BASE_INDEX = REDSOUND_SE_TRACK_COUNT,
	REDSOUND_VOICE_COUNT = 0x40,
	REDSOUND_EDITOR_VOICE_COUNT = 2,
	REDSOUND_VOICE_SIZE = sizeof(RedVoiceDATA),
	REDSOUND_VOICE_BUFFER_SIZE = REDSOUND_VOICE_SIZE * REDSOUND_VOICE_COUNT,
	REDSOUND_KEY_ON_BUFFER_SIZE = sizeof(RedKeyOnDATA),
	REDSOUND_REVERB_DEPTH_COUNT = 2,
	REDSOUND_REVERB_DEPTH_BUFFER_SIZE = REDSOUND_REVERB_DEPTH_SIZE * REDSOUND_REVERB_DEPTH_COUNT,
	REDSOUND_MUTE_WORD_COUNT = 2,
	REDSOUND_MUTE_WORD_SHIFT = 5,
	REDSOUND_MUTE_BITS_PER_WORD = 1 << REDSOUND_MUTE_WORD_SHIFT,
	REDSOUND_STREAM_COUNT = 4,
	REDSOUND_STREAM_BUFFER_SIZE = sizeof(RedStreamDATA) * REDSOUND_STREAM_COUNT,
};

enum RedReverbDepthIndex {
	REDSOUND_REVERB_DEPTH_MUSIC = 0,
	REDSOUND_REVERB_DEPTH_SE = 1,
	REDSOUND_REVERB_BANK_MASK = REDSOUND_REVERB_DEPTH_SE,
};

enum RedMuteWordIndex {
	REDSOUND_MUTE_LOW_WORD = 0,
	REDSOUND_MUTE_HIGH_WORD = 1,
};

enum RedSoundFixedPoint {
	REDSOUND_FIXED_SHIFT = 12,
	REDSOUND_FIXED_HALF = 0x800,
	REDSOUND_FIXED_ONE = 0x1000,
	REDSOUND_FIXED_WHOLE_MASK = ~(REDSOUND_FIXED_ONE - 1),
	REDSOUND_VOLUME_BYTE_SCALE = 0x100,
	REDSOUND_VOLUME_FULL = 0x7FFF000,
	REDSOUND_VOLUME_DEFAULT = 0x7F000,
	REDSOUND_VOLUME_MAX = 0x7F,
	REDSOUND_ENVELOPE_LEVEL_FULL = 0x8000,
	REDSOUND_AX_MIX_MAX = 0x7FFF,
	REDSOUND_AX_MIX_SHIFT = 15,
	REDSOUND_COMMAND_VALUE_MASK = 0x7F,
	REDSOUND_CONTROL_TICK_PERIOD = 0xFA,
	REDSOUND_SE_TICK_STEP = 0x78,
	REDSOUND_FRAMES_PER_SECOND = 60,
	REDSOUND_SE_FADE_TICKS_PER_SECOND = 0x60,
	REDSOUND_MUSIC_FADE_TICKS_PER_SECOND = 200,
	REDSOUND_STREAM_FADE_TICKS_PER_SECOND = REDSOUND_MUSIC_FADE_TICKS_PER_SECOND,
	REDSOUND_MUSIC_ID_MIN = 0,
	REDSOUND_MUSIC_ID_NONE = -1,
	REDSOUND_MUSIC_PLAY_FAILED = -1,
	REDSOUND_SE_ID_MIN = 0,
	REDSOUND_SE_ID_NONE = 0,
	REDSOUND_SE_ID_ALL = -1,
	REDSOUND_SE_PLAY_FAILED = -1,
	REDSOUND_SE_BANK_SESEP = -1,
	REDSOUND_SESEP_ID_NONE = -1,
	REDSOUND_SE_MG_ID_DIVISOR = 1000,
	REDSOUND_TEMPO_SCALE_MASK = 0xFFFF,
	REDSOUND_TEMPO_SCALE_SHIFT = 0x10,
	REDSOUND_TEMPO_SCALE_POSITIVE_SHIFT = 0x0F,
	REDSOUND_PITCH_NOTE_SHIFT = 8,
	REDSOUND_PITCH_NOTE_UNIT = 0x100,
	REDSOUND_PITCH_BASE_NOTE_SHIFT = 0x14,
	REDSOUND_PITCH_WAVE_SHIFT = 0x10,
	REDSOUND_PITCH_KEY_SIGNATURE_UNIT = 0x100000,
	REDSOUND_PITCH_NOTE_MASK = 0x7F,
	REDSOUND_PITCH_FINE_MASK = 0xFF,
	REDSOUND_PITCH_FINE_COUNT = REDSOUND_PITCH_FINE_MASK + 1,
	REDSOUND_PITCH_FINE_TUNE_POSITIVE_SHIFT = 7,
	REDSOUND_PITCH_FINE_TUNE_NEGATIVE_SHIFT = 8,
	REDSOUND_PITCH_OCTAVE_UNITS = 0xC00,
	REDSOUND_PITCH_TONE_SHIFT = 10,
	REDSOUND_SIGN_SHIFT = 0x1F,
	REDSOUND_NOTES_PER_OCTAVE = 12,
	REDSOUND_PAN_BYTE_CENTER = 0x40,
	REDSOUND_PAN_BYTE_MASK = 0x7F,
	REDSOUND_PAN_BYTE_SIGN_BIT = 0x80,
	REDSOUND_PAN_BYTE_WRAP = 0x100,
	REDSOUND_PAN_TABLE_COUNT = REDSOUND_PAN_BYTE_WRAP,
	REDSOUND_MASTER_VOLUME_SCALE = 4,
	REDSOUND_MASTER_VOLUME_FULL = (REDSOUND_COMMAND_VALUE_MASK + 1) * REDSOUND_MASTER_VOLUME_SCALE - 1,
	REDSOUND_MASTER_VOLUME_FULL_FIXED = REDSOUND_MASTER_VOLUME_FULL * REDSOUND_FIXED_ONE,
	REDSOUND_MASTER_VOLUME_FULL_FIXED_HALF = REDSOUND_MASTER_VOLUME_FULL_FIXED + REDSOUND_FIXED_HALF,
	REDSOUND_PAN_CENTER = 0x40000,
};

enum RedSoundPauseState {
	REDSOUND_PAUSE_OFF = 0,
	REDSOUND_PAUSE_ON = 1,
};

enum RedSoundReportPrintState {
	REDSOUND_REPORT_PRINT_OFF = 0,
	REDSOUND_REPORT_PRINT_ON = 1,
};

enum RedMusicSkipCompleteState {
	REDSOUND_MUSIC_SKIP_NOT_COMPLETE = 0,
	REDSOUND_MUSIC_SKIP_COMPLETE = 1,
};

enum RedMusicPhraseStopState {
	REDSOUND_MUSIC_PHRASE_STOP_OFF = 0,
	REDSOUND_MUSIC_PHRASE_STOP_ON = 1,
};

enum RedSeVolumeQueryMode {
	REDSOUND_SE_VOLUME_QUERY_VALUE = 0,
	REDSOUND_SE_VOLUME_QUERY_DELTA = 1,
};

enum RedSoundTableLayout {
	REDSOUND_TONE_PITCH_TABLE_OFFSET = 0,
	REDSOUND_TONE_PITCH_TABLE_SIZE = sizeof(u32) * REDSOUND_NOTES_PER_OCTAVE,
	REDSOUND_TONE_PITCH_TABLE_ALLOC_SIZE = REDSOUND_TONE_PITCH_TABLE_SIZE,
	REDSOUND_FINE_PITCH_TABLE_OFFSET = REDSOUND_TONE_PITCH_TABLE_OFFSET + REDSOUND_TONE_PITCH_TABLE_SIZE,
	REDSOUND_FINE_PITCH_TABLE_SIZE = sizeof(int) * REDSOUND_PITCH_FINE_COUNT,
	REDSOUND_FINE_PITCH_TABLE_ALLOC_SIZE = REDSOUND_FINE_PITCH_TABLE_SIZE,
	REDSOUND_KEY_SIGNATURE_INDEX_TABLE_OFFSET = REDSOUND_FINE_PITCH_TABLE_OFFSET + REDSOUND_FINE_PITCH_TABLE_SIZE,
	REDSOUND_KEY_SIGNATURE_INDEX_TABLE_SIZE = sizeof(int) * REDSOUND_KEY_SIGNATURE_INDEX_COUNT,
	REDSOUND_KEY_SIGNATURE_INDEX_TABLE_ALLOC_SIZE = REDSOUND_KEY_SIGNATURE_INDEX_TABLE_SIZE,
	REDSOUND_KEY_SIGNATURE_DATA_TABLE_OFFSET =
	    REDSOUND_KEY_SIGNATURE_INDEX_TABLE_OFFSET + REDSOUND_KEY_SIGNATURE_INDEX_TABLE_SIZE,
	REDSOUND_KEY_SIGNATURE_DATA_TABLE_SIZE = sizeof(signed char) * REDSOUND_KEY_SIGNATURE_DATA_COUNT,
	REDSOUND_KEY_SIGNATURE_DATA_TABLE_ALLOC_SIZE = REDSOUND_KEY_SIGNATURE_DATA_TABLE_SIZE,
	REDSOUND_RANDOM_DATA_TABLE_OFFSET =
	    REDSOUND_KEY_SIGNATURE_DATA_TABLE_OFFSET + REDSOUND_KEY_SIGNATURE_DATA_TABLE_SIZE,
	REDSOUND_RANDOM_DATA_TABLE_SIZE = sizeof(signed char) * REDSOUND_RANDOM_DATA_COUNT,
	REDSOUND_RANDOM_DATA_TABLE_ALLOC_SIZE = REDSOUND_RANDOM_DATA_TABLE_SIZE,
	REDSOUND_PAN_TABLE_OFFSET = REDSOUND_RANDOM_DATA_TABLE_OFFSET + REDSOUND_RANDOM_DATA_TABLE_SIZE,
	REDSOUND_PAN_TABLE_SIZE = sizeof(s16) * REDSOUND_PAN_TABLE_COUNT,
	REDSOUND_PAN_TABLE_ALLOC_SIZE = REDSOUND_PAN_TABLE_SIZE,
	REDSOUND_PAN_TABLE_R_OFFSET = REDSOUND_PAN_TABLE_OFFSET + REDSOUND_PAN_TABLE_SIZE,
	REDSOUND_PAN_TABLE_PAIR_SIZE = REDSOUND_PAN_TABLE_SIZE * 2,
	REDSOUND_PAN_TABLE_PAIR_ALLOC_SIZE = REDSOUND_PAN_TABLE_PAIR_SIZE,
	REDSOUND_EXECUTE_DATA_TABLE_END_OFFSET = REDSOUND_PAN_TABLE_R_OFFSET + REDSOUND_PAN_TABLE_SIZE,
	REDSOUND_EXECUTE_DATA_TABLE_SIZE =
	    REDSOUND_TONE_PITCH_TABLE_SIZE + REDSOUND_FINE_PITCH_TABLE_SIZE +
	    REDSOUND_KEY_SIGNATURE_INDEX_TABLE_SIZE + REDSOUND_KEY_SIGNATURE_DATA_TABLE_SIZE +
	    REDSOUND_RANDOM_DATA_TABLE_SIZE + REDSOUND_PAN_TABLE_PAIR_SIZE,
	REDSOUND_EXECUTE_DATA_TABLE_ALLOC_SIZE = REDSOUND_EXECUTE_DATA_TABLE_SIZE,
};

struct RedSeBlockHEAD;

extern RedMidiControlFunc p_MidiControl_Function[REDSOUND_MIDI_CONTROL_FUNCTION_COUNT];
extern u32 t_TonePitch[REDSOUND_NOTES_PER_OCTAVE];
#define RedTonePitchGet(index) (t_TonePitch[(index)])
extern int t_FinePitch[REDSOUND_PITCH_FINE_COUNT];
#define RedFinePitchGet(index) (t_FinePitch[(index)])
extern int t_KeySignatureIndex[REDSOUND_KEY_SIGNATURE_INDEX_COUNT];
#define RedKeySignatureIndexGet(index) (t_KeySignatureIndex[(index)])
extern signed char t_KeySignatureData[REDSOUND_KEY_SIGNATURE_DATA_COUNT];
#define RedKeySignatureDataGet(offset) (t_KeySignatureData + (offset))
#define RedKeySignatureGetDefaultData() (t_KeySignatureData + REDSOUND_KEY_SIGNATURE_DEFAULT_DATA_OFFSET)
extern signed char t_RandomData[REDSOUND_RANDOM_DATA_COUNT];
#define RedRandomDataGetAddress(index) (t_RandomData + (index))
#define RedRandomDataGet(index) (t_RandomData[(index)])
extern s16 t_PanningData[REDSOUND_PAN_TABLE_COUNT];
#define RedPanningDataGet(index) (t_PanningData[(index)])
extern s16 t_PanningDataR[REDSOUND_PAN_TABLE_COUNT];
#define RedPanningDataRGet(index) (t_PanningDataR[(index)])
extern u32 m_TerminateNote[];
extern volatile unsigned int m_AutoID;
extern CRedEntry c_RedEntry;
extern OSSemaphore m_MusicSkipSemaphore;
extern RedSeBlockHEAD* volatile p_SeBlockData[REDSOUND_SE_BLOCK_BANK_COUNT];
#define RedSeBlockDataGet(index) (p_SeBlockData[(index)])
extern u8* volatile p_ZeroData;
extern RedSoundCONTROL* volatile p_SoundControlBuffer;
#define RedSoundControlGet(index) (p_SoundControlBuffer + (index))
#define RedSoundControlGetMusicPlayEnd() RedSoundControlGet(REDSOUND_CONTROL_MUSIC_PLAY_END)
#define RedSoundControlGetMusicAllEnd() RedSoundControlGet(REDSOUND_CONTROL_MUSIC_ALL_END)
extern RedSoundCONTROL* volatile p_SoundControl;
extern volatile int m_KeyOnEntry;
extern RedKeyOnDATA* volatile p_KeyOnData;
extern int m_SoundPlayMode;
extern int m_SoundMasterControl;
extern volatile int m_ReportPrint;
extern int m_MusicFastSpeed;
extern volatile int m_MusicSkipLine;
extern int m_MusicKeySignature;
extern int* volatile p_MusicReplayPoint;
#define RedMusicReplayPointGet(index) (p_MusicReplayPoint + (index))
extern RedControlRamp* volatile p_MusicTempoControl;
extern RedControlRamp* volatile p_MusicPitchControl;
extern int m_MusicPhraseStop;
extern int m_CrossTime;
extern volatile int m_MasterMusicVolume;
extern volatile int m_MasterSEVolume;
extern RedStreamDATA* volatile p_Stream;
#define RedStreamDataGetEnd() (p_Stream + REDSOUND_STREAM_COUNT)
extern volatile int m_SeSkipStep;
extern RedVoiceDATA* volatile p_VoiceData;
#define RedVoiceDataGetBegin() (p_VoiceData)
#define RedVoiceDataGet(index) (p_VoiceData + (index))
#define RedVoiceDataGetEnd() (p_VoiceData + REDSOUND_VOICE_COUNT)
extern int p_EditorVoice[REDSOUND_EDITOR_VOICE_COUNT];
#define RedEditorVoiceGet(index) (p_EditorVoice + (index))
#define RedEditorVoiceGetEnd() (p_EditorVoice + REDSOUND_EDITOR_VOICE_COUNT)
extern RedTrackDATA* p_EditorTrack;
extern OSThread m_MusicSkipThread;
extern u8* volatile p_MusicSkipThreadStack;
extern volatile int m_MusicSkipComplete;
extern RedReverbDepth* volatile p_ReverbDepth;
#define RedReverbDepthGet(index) (p_ReverbDepth + (index))
extern unsigned int m_Mute[REDSOUND_MUTE_WORD_COUNT];
#define RedMuteGetWord(voiceNo) (m_Mute[(voiceNo) / REDSOUND_MUTE_BITS_PER_WORD])
#define RedMuteGetMask(voiceNo) (1U << ((voiceNo) % REDSOUND_MUTE_BITS_PER_WORD))
extern CRedMemory c_RedMemory;
extern volatile u32 m_ChangeStatus;
extern CRedDriver c_Driver;

#endif
