import contextlib
import io
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from tools.project import (
    Object, ProgressCategory, ProjectConfig, calculate_progress,
    generate_build_ninja, generate_objdiff_config,
)


class ProjectSourceBuildTests(unittest.TestCase):
    def generate(self, units):
        config = ProjectConfig()
        config.version = "TEST"
        config.config_path = Path("config.yml")
        config.check_sha_path = Path("build.sha1")
        config.linker_version = "GC/test"
        config.compilers_tag = "test"
        config.binutils_tag = "test"
        config.dtk_tag = "v1.0.0"
        config.objdiff_tag = "v1.0.0"
        config.sjiswrap_tag = "v1.0.0"
        config.wrapper = Path("wine")
        config.asflags = []
        config.ldflags = []
        config.libs = [{
            "lib": "test", "cflags": [],
            "objects": [Object(False, "present.c"),
                        Object(False, "disabled.c", add_to_all=False),
                        Object(False, "missing.c")],
        }]
        build_config = {
            "name": "main", "module_id": 0, "entry": "_start",
            "ldscript": "ldscript.lcf", "units": units,
            "modules": [], "links": [{"modules": ["main"]}],
            "version": "1.0.0",
        }
        with tempfile.TemporaryDirectory() as temp:
            previous = Path.cwd()
            try:
                os.chdir(temp)
                Path("src").mkdir()
                Path("src/present.c").write_text("int present(void) { return 1; }\n")
                Path("src/disabled.c").write_text("int disabled(void) { return 2; }\n")
                with patch("tools.project._listdir_cache", {}):
                    generate_build_ninja(config, config.objects(), build_config)
                return Path("build.ninja").read_text().replace("\\", "/").replace("$\n    ", "")
            finally:
                os.chdir(previous)

    def test_unmapped_sources_compile_without_entering_retail_link(self):
        text = self.generate([])
        self.assertIn("build build/TEST/src/present.o: mwcc", text)
        self.assertIn("build all_source: phony build/TEST/src/present.o", text)
        self.assertNotIn("build build/TEST/src/disabled.o:", text)
        self.assertNotIn("build build/TEST/src/missing.o:", text)
        link = next(line for line in text.splitlines() if line.startswith("build build/TEST/main.elf:"))
        self.assertNotIn("present.o", link)

    def test_existing_unit_keeps_one_compile_rule_and_retail_input(self):
        text = self.generate([{"name": "present.c", "object": "original/present.o", "autogenerated": False}])
        self.assertEqual(text.count("build build/TEST/src/present.o:"), 1)
        link = next(line for line in text.splitlines() if line.startswith("build build/TEST/main.elf:"))
        self.assertIn("original/present.o", link)
        self.assertNotIn("src/present.o", link)


class ProjectProgressCategoryTests(unittest.TestCase):
    def generate(self, object_categories, target_names):
        config = ProjectConfig()
        config.version = "TEST"
        config.progress_categories = [
            ProgressCategory(name, name) for name in
            ("game", "redsound", "sdk", "gba_cli", "gba_mgr", "unused")
        ]
        config.libs = [{
            "lib": name, "cflags": [], "mw_version": "GC/2.5",
            "progress_category": category,
            "objects": [Object(False, name + ".c")],
        } for name, category in object_categories.items()]
        config.extra_objdiff_units = [{
            "name": program + "/main", "target_path": program + ".o",
            "metadata": {"complete": False, "progress_categories": [program]},
        } for program in ("gba_cli", "gba_mgr")]
        build_config = {
            "name": "main", "modules": [],
            "units": [{"name": name, "object": "original/" + name + ".o",
                       "autogenerated": name.startswith("auto_")}
                      for name in target_names],
        }
        with tempfile.TemporaryDirectory() as temp:
            previous = Path.cwd()
            try:
                os.chdir(temp)
                Path("src").mkdir()
                for name in object_categories:
                    Path("src", name + ".c").write_text("void function(void) {}\n")
                with patch("tools.project._listdir_cache", {}):
                    generate_objdiff_config(config, config.objects(), build_config)
                return json.loads(Path("objdiff.json").read_text())
            finally:
                os.chdir(previous)

    def test_unmapped_gc_is_classified_without_inventing_source_ownership(self):
        result = self.generate(
            {"mapped": "sdk", "uncategorized": None},
            ["mapped.c", "uncategorized.c", "auto_text", "unclaimed.c"],
        )
        categories = {c["id"]: c["name"] for c in result["progress_categories"]}
        self.assertEqual(set(categories), {"sdk", "unclassified_gc", "gba_cli", "gba_mgr"})
        self.assertEqual(categories["unclassified_gc"], "Unclassified GameCube")
        units = {u["name"]: u for u in result["units"]}
        for name in ("main/auto_text", "main/unclaimed"):
            self.assertEqual(units[name]["metadata"]["progress_categories"], ["unclassified_gc"])
            self.assertNotIn("base_path", units[name])
            self.assertNotIn("complete", units[name]["metadata"])
        self.assertEqual(units["main/uncategorized"]["metadata"]["progress_categories"], ["unclassified_gc"])
        self.assertEqual(units["main/mapped"]["metadata"]["progress_categories"], ["sdk"])
        for program in ("gba_cli", "gba_mgr"):
            self.assertEqual(units[program + "/main"]["metadata"],
                             {"complete": False, "progress_categories": [program]})

    def test_mapped_library_and_gba_categories_are_preserved(self):
        result = self.generate(
            {"game": "game", "redsound": "redsound", "sdk": "sdk"},
            ["game.c", "redsound.c", "sdk.c"],
        )
        self.assertEqual([c["id"] for c in result["progress_categories"]],
                         ["game", "redsound", "sdk", "gba_cli", "gba_mgr"])
        for unit in result["units"]:
            category = (unit["name"].split("/")[-1] if unit["name"].startswith("main/")
                        else unit["name"].split("/")[0])
            self.assertEqual(unit["metadata"]["progress_categories"], [category])

    def test_progress_omits_empty_categories_in_existing_reports(self):
        with tempfile.TemporaryDirectory() as temp:
            config = ProjectConfig()
            config.version = "TEST"
            config.build_dir = Path(temp)
            measures = {"total_code": "4", "total_units": 1}
            report = {"measures": measures, "categories": [
                {"id": "empty", "name": "Empty", "measures": {
                    "matched_code_percent": 100.0, "total_code": "0", "total_data": "0"}},
                {"id": "sdk", "name": "SDK", "measures": measures},
            ]}
            config.out_path().mkdir(parents=True)
            (config.out_path() / "report.json").write_text(json.dumps(report))
            output = io.StringIO()
            with patch.object(config, "validate"), patch.dict(os.environ, {"GITHUB_STEP_SUMMARY": ""}), contextlib.redirect_stdout(output):
                calculate_progress(config)
            self.assertNotIn("Empty:", output.getvalue())
            self.assertIn("SDK:", output.getvalue())


if __name__ == "__main__":
    unittest.main()
