#include "global.h"

#if defined(VERSION_GCCJGC)
#include "msg_sys_jp.inc"
#else

char *gTribeNames_En[] = {
    "Clavat",
    "Lilty",
    "Yuke",
    "Selkie",
};

char *gTribeNames_De[] = {
    "Clavat",
    "Lilty",
    "Yuke",
    "Selkie",
};

char *gTribeNames_It[] = {
    "Clavat",
    "Lility",
    "Yuke",
    "Seliky",
};

char *gTribeNames_Fr[] = {
    "Clavat",
    "Lilty",
    "Yuke",
    "Selkie",
};

char *gTribeNames_Es[] = {
    "Clavate",
    "Lilti",
    "Yuko",
    "Selki",
};

char *gSystemText_En[] = {
    "",
    "Memories",
    "Yes",
    "No",
    "Cancel",
    "gil",
    "STR",
    "DEF",
    "MAG",
    "Attack",
    "Remove",
    "Buy",
    "Sell",
    "g.",
    "Money / Price",
    "Quantity:",
    "Strength",
    "For:",
    "/",
    ":",
    "x",
    "Money",
    "Fee",
    "Materials",
    "Stock",
    "Craft",
    "Equip",
    "Male",
    "Female",
    "All",
    "HP",
    "",
    "Items:",
    "Use",
    "Drop",
    "Destroy",
    "Defend",
    "Equip",
    "Cannot sell.",
    "+",
    "\xB1",
    "???",
    "None carried.",
    "Treasures",
    "Radar",
    "Command List",
    "Items",
    "Equip",
    "Artefacts",
    "Treasures",
    "Money",
    "Favorites",
    "Family",
    "Letters",
    "Father",
    "Mother",
    "Brother",
    "Sister",
    "Brother",
    "Sister",
    "",
    "Letters",
    "None",
    "Defense",
    "Favourites",
    "Defence",
};

char *gSystemText_De[] = {
    "",
    "Erinnerungen",
    "Ja",
    "Nein",
    "Abbrechen",
    "Gil",
    "STR",
    "ABW",
    "MAG",
    "Angreifen",
    "Ablegen",
    "Kaufen",
    "Verkaufen",
    "G",
    "Guthaben/Preis",
    "Anzahl x",
    "St\xE4rke",
    "F\xFCr:",
    "/",
    ":",
    "x",
    "Guthaben",
    "Kosten",
    "Ben\xF6tigt",
    "Inventar",
    "Herstellen",
    "Ausr\xFCsten",
    "M\xE4nnlich",
    "Weiblich",
    "Alle Rassen",
    "HP",
    "-",
    "Hinterl\xE4sst:",
    "Benutzen",
    "Wegwerfen",
    "Zerst\xF6ren",
    "Verteidigen",
    "Ausr\xFCsten",
    "Unverk\xE4ufl.",
    "+",
    "\xB1",
    "???",
    "Nicht vorhanden",
    "Vorl\xE4ufige Artefakte",
    "Radar",
    "Kommandoliste",
    "Gegenst\xE4nde",
    "Ausr\xFCsten",
    "Artefakte",
    "Geborgtes",
    "Geld",
    "Geschmack",
    "Familie",
    "Briefe",
    "Vater",
    "Mutter",
    "Bruder",
    "Schwester",
    "kl. Bruder",
    "kl. Schwester",
    "",
    "Liste erhaltener Briefe",
    "Keinen Gegenstand",
    "Abwehr",
};

char *gSystemText_It[] = {
    "",
    "Memorie",
    "S\xEC",
    "No",
    "Annulla",
    "guil",
    "Forza",
    "Difesa",
    "Magia",
    "Attacco",
    "Rimuovi",
    "Compra",
    "Vendi",
    "g.",
    "Denaro / Prezzo",
    "Quantit\xE0:",
    "Forza",
    "Per:",
    "/",
    ":",
    "x",
    "Denaro",
    "Tariffa",
    "Materie",
    "Scorta",
    "Arte",
    "Equip.",
    "Maschio",
    "Femmina",
    "Tutti",
    "PV",
    "",
    "Oggetti:",
    "Usa",
    "Posa",
    "Distruggi",
    "Difesa",
    "Equip.",
    "Non puoi vendere.",
    "+",
    "\xB1",
    "???",
    "Non ne possiedi.",
    "Tesori",
    "Radar",
    "Lista Comandi",
    "Oggetti",
    "Equip.",
    "Manufatti",
    "Tesori",
    "Denaro",
    "Preferiti",
    "Famiglia",
    "Lettere",
    "Padre",
    "Madre",
    "Fratello",
    "Sorella",
    "Fratello",
    "Sorella",
    "",
    "Lettere",
    "Nessuno",
    "Difesa",
};

char *gSystemText_Fr[] = {
    "",
    "Souvenirs",
    "Oui",
    "Non",
    "Annuler",
    "gils",
    "FOR",
    "RES",
    "MAG",
    "Attaquer",
    "Retirer",
    "Acheter",
    "Vendre",
    "g.",
    "Argent / Prix",
    "Quantit\xE9:",
    "Force",
    "Pour",
    "/",
    ":",
    "x",
    "Argent",
    "Tarif",
    "Mat\xE9riaux",
    "En stock",
    "Forger",
    "Equiper",
    "Masculin",
    "F\xE9minin",
    "Tous",
    "PV",
    "",
    "Objets:",
    "Utiliser",
    "Jeter",
    "D\xE9truir.",
    "D\xE9" "fendre",
    "Equiper",
    "Non vendable",
    "+",
    "\xB1",
    "???",
    "0 en stock",
    "Tr\xE9sors",
    "Carte",
    "Commandes",
    "Objets",
    "Equiper",
    "Artefacts",
    "Tr\xE9sors",
    "Gils",
    "Pr\xE9" "f\xE9rences",
    "Famille",
    "Lettres",
    "P\xE8re",
    "M\xE8re",
    "Fr\xE8re",
    "S\x9Cur",
    "Fr\xE8re",
    "S\x9Cur",
    "",
    "Lettres",
    "aucun",
    "R\xE9sistance",
};

char *gSystemText_Es[] = {
    "",
    "Memorias",
    "S\xED",
    "No",
    "Cancelar",
    "guiles",
    "Fuerza",
    "Defensa",
    "Magia",
    "Atacar",
    "Quitar",
    "Comprar",
    "Vender",
    "g.",
    "Dinero / Precio",
    "Cantidad:",
    "Fuerza",
    "Para:",
    "/",
    ":",
    "x",
    "Dinero",
    "Honorario",
    "Materiales",
    "Reservas",
    "Artesan\xED" "a",
    "Equipar",
    "Hombre",
    "Mujer",
    "Todos",
    "VIT",
    "",
    "Objetos:",
    "Utilizar",
    "Descartar",
    "Destruir",
    "Defender",
    "Equipa",
    "No vendible.",
    "+",
    "\xB1",
    "\xBF\xBF??",
    "Sin reservas.",
    "Tesoros",
    "Mapa",
    "Comandos",
    "Objetos",
    "Equipo",
    "Artefactos",
    "Tesoros",
    "Dinero",
    "Favoritos",
    "Familia",
    "Cartas",
    "Padre",
    "Madre",
    "Hermano",
    "Hermana",
    "Hermano",
    "Hermana",
    "",
    "Cartas",
    "Ninguno",
    "Defensa",
};

char *gJobNames_En[] = {
    "Blacksmith",
    "Tailor",
    "Farmer",
    "Rancher",
    "Miller",
    "Fisherman",
    "Merchant",
    "Alchemist",
};

char *gJobNames_De[] = {
    "Schmied",
    "Schneider",
    "Bauer",
    "Viehz\xFC" "chter",
    "M\xFCller",
    "Fischer",
    "H\xE4ndler",
    "Alchemist",
};

char *gJobNames_It[] = {
    "Fabbri",
    "Sarti",
    "Agricoltori",
    "Allevatori",
    "Mugnai",
    "Pescatori",
    "Mercanti",
    "Alchimisti",
};

char *gJobNames_Fr[] = {
    "Forgeron",
    "Tailleur",
    "Fermier",
    "\xC9leveur",
    "Meunier",
    "P\xEA" "cheur",
    "Marchand",
    "Alchimiste",
};

char *gJobNames_Es[] = {
    "Herrero",
    "Sastre",
    "Campesino",
    "Granjero",
    "Molinero",
    "Pescador",
    "Comerciante",
    "Alquimista",
};

char *gStatNames_En[] = {
    "Resist fire +1",
    "Resist cold +1",
    "Resist lightning +1",
    "Resist slow +1",
    "Resist prlysis. +1",
    "Resist poison +1",
    "Resist curses +1",
    "Resist petrif. +1",
    "Casting time",
    "Charge time",
    "Spell duration",
    "Spell duration",
    "Resist miasma",
    "Long spell range",
    "Long focus attks.",
    "Regen",
    "Focus attacks",
    "Spell damage",
    "Cannot be stunned",
};

char *gStatNames_De[] = {
    "Feuer-R.: +1",
    "Eis-R.: +1",
    "Blitz-R.: +1",
    "Gemach-R.: +1",
    "Stopp-R.: +1",
    "Gift-R.: +1",
    "Fluch-R.: +1",
    "Stein-R.: +1",
    "Z. laden:",
    "Sammeln:",
    "Z. wirkt:",
    "Z. wirkt:",
    "Miasma-R. +",
    "Z.-Reichw. +",
    "SA-Reichw. +",
    "Regena",
    "Spezialattacke:",
    "Zauber-Schaden:",
    "Standfest",
};

char *gStatNames_It[] = {
    "Antifuoco +1",
    "Antigelo +1",
    "Antituono +1",
    "Antislow +1",
    "Antistop +1",
    "Antiveleno +1",
    "Antimalediz. +1",
    "Antipietrif. +1",
    "Carica magia",
    "Carica attacchi",
    "Durata magie",
    "Durata magie",
    "Antimiasma",
    "Portata magie",
    "Portata Super Att.",
    "Rigenerazione",
    "Super Attacchi",
    "Danno Magico",
    "Antistordimento",
};

char *gStatNames_Fr[] = {
    "Anti-Feu +1",
    "Anti-Glace +1",
    "Anti-Foudre +1",
    "Anti-Somni +1",
    "Anti-Stop +1",
    "Anti-Poison +1",
    "Anti-Mal\xE9" "fice +1",
    "Anti-P\xE9trif. +1",
    "Tps lancement",
    "Tps de charge",
    "Dur\xE9" "e sorts",
    "Dur\xE9" "e sorts",
    "Anti-Miasme",
    "Port\xE9" "e des sorts",
    "Port\xE9" "e super-atq.",
    "R\xE9" "cup",
    "Super-attaques",
    "D\xE9g\xE2ts magiq.",
    "Rend in\xE9" "branlable",
};

char *gStatNames_Es[] = {
    "Anti-fuego +1",
    "Anti-fr\xEDo +1",
    "Anti-rayos +1",
    "Anti-Freno +1",
    "Anti-Paro +1",
    "Anti-veneno +1",
    "Anti-maldic. +1",
    "Anti-petrif. +1",
    "Tiempo lanzam.",
    "Tiempo carga",
    "Durac. hechiz.",
    "Durac. hechiz.",
    "Anti-miasma",
    "Alcance hechiz.",
    "Alc. superataq.",
    "Revitalia",
    "Superataque",
    "Da\xF1os m\xE1gicos",
    "No se aturde",
};

char *gNoticeText_En[] = {
    "Cannot use this name.",
    "That appearance is already taken.",
    "That trade is already taken.",
    "Please look at the TV screen.",
    "Waiting for connection...",
    "Downloading...",
    "PAUSE",
};

char *gNoticeText_De[] = {
    "Bereits vergeben.",
    "Bereits vergeben.",
    "Bereits vergeben.",
    "Auf den TV-Bildschirm gucken!",
    "Warten auf Verbindung...",
    "Laden...",
    "Pause",
};

char *gNoticeText_It[] = {
    "Non puoi usare questo nome.",
    "Questo aspetto \xE8 gi\xE0 in uso.",
    "Questo mestiere \xE8 gi\xE0 in uso.",
    "Guarda lo schermo del televisore.",
    "Connessione in corso...",
    "Trasferimento in corso...",
    "PAUSA",
};

char *gNoticeText_Fr[] = {
    "Ce nom est d\xE9j\xE0 pris.",
    "Cette apparence est d\xE9j\xE0 prise.",
    "Ce m\xE9tier est d\xE9j\xE0 pris.",
    "Veuillez regarder le t\xE9l\xE9viseur",
    "Connexion en attente",
    "Chargement en cours...",
    "PAUSE",
};

char *gNoticeText_Es[] = {
    "No es posible usar este nombre.",
    "Esta raza ya est\xE1 en uso.",
    "Este oficio ya est\xE1 en uso.",
    "Por favor mira la pantalla de TV.",
    "Conectando...",
    "Descargando...",
    "Pausa",
};

char *gTraitNames_En[] = {
    "Flying undead",
    "Holy and Gravity are effective",
    "Flying",
    "Cripple with Gravity",
    "Undead",
    "Holy makes it appear",
    "Vulnerable to magic",
    "Resistant to magic",
    "Vulnerable to fire",
    "Resistant to fire",
    "Vulnerable to cold",
    "Resistant to cold",
    "Vulnerable to lightning",
    "Resistant to lightning",
    "Vulnerable to slow",
    "Vulnerable to paralysis",
    "Resistant to gravity",
    "Vulnerable to gravity",
};

char *gTraitNames_De[] = {
    "Untot, fliegt",
    "Hilft: Gravit. Sanct.",
    "Fliegt",
    "Gravitas ist effektiv",
    "Untot",
    "Sanctus ist effektiv",
    "Hasst Zauber",
    "Mag Zauber",
    "Hasst Feuer",
    "Mag Feuer",
    "Hasst Eis",
    "Mag Eis",
    "Hasst Blitz",
    "Mag Blitz",
    "Hasst Gemach",
    "Hasst Stopp",
    "Mag Gravitas",
    "Hasst Gravitas",
};

char *gTraitNames_It[] = {
    "Non-morto volante",
    "Sono efficaci Sancta e Antima",
    "Volante",
    "Abbattile con Antima",
    "Non-morto",
    "Colpiscilo con Sancta",
    "Vulnerabile alla magia",
    "Resistente alla magia",
    "Vulnerabile al Fuoco",
    "Resistente al Fuoco",
    "Vulnerabile al Gelo",
    "Resistente al Gelo",
    "Vulnerabile al Tuono",
    "Resistente al Tuono",
    "Vulnerabile a Slow",
    "Vulnerabile a Stop",
    "Resistente ad Antima",
    "Vulnerabile ad Antima",
};

char *gTraitNames_Fr[] = {
    "*Mort-vivant volant",
    "*Craint Sid\xE9ral/Gravit\xE9",
    "*Ennemi volant",
    "*Craint Gravit\xE9",
    "*Mort-vivant",
    "*Craint Sid\xE9ral",
    "*Craint la magie",
    "*R\xE9siste \xE0 la magie",
    "*Craint Brasier",
    "*R\xE9siste \xE0 Brasier",
    "*Craint Glacier",
    "*R\xE9siste \xE0 Glacier",
    "*Craint Foudre",
    "*R\xE9siste \xE0 Foudre",
    "*Craint Somni",
    "*Craint Stop",
    "*R\xE9siste \xE0 Gravit\xE9",
    "*Craint Gravit\xE9",
};

char *gTraitNames_Es[] = {
    "Muerto Viv. volador",
    "Usar Sanctus y Gravedad.",
    "Volador",
    "Hiere con Gravedad.",
    "Muerto Viviente",
    "Aparece con Sanctus",
    "Vulnerable a la magia",
    "Resistente a la magia",
    "Vulnerable al fuego",
    "Resiste el fuego",
    "Vulnerable al fr\xEDo",
    "Resistente al fr\xEDo",
    "Vulnerable a los rayos",
    "Resistente a los rayos",
    "Vulnerable al Freno",
    "Vulnerable al Paro",
    "Resiste Gravedad",
    "Vulnerab. Gravedad",
};

char *gLookNames_En[] = {
    "Cowlick",
    "Natural",
    "Headband",
    "Cap",
    "Long Hair",
    "Short Hair",
    "Dark Coat",
    "White Cap",
    "Bare Head",
    "Horned Helm",
    "Steel Visor",
    "Bucket Head",
    "Bare Head",
    "Blue Armor",
    "Elegant",
    "Red Mask",
    "One Horn",
    "Bumpy",
    "Long Beak",
    "Black Mage",
    "Spiral",
    "Tulip",
    "Spoon",
    "Heart Top",
    "Wolfie",
    "Shark Eyes",
    "Bandanna",
    "Raccoon Tail",
    "Wolfie",
    "Raccoon Tail",
    "Shark Eyes",
    "Owl Head",
};

char *gLookNames_De[] = {
    "Spitzschopf",
    "Wuschel",
    "Stirnband",
    "Kopftuch",
    "lange Haare",
    "kurze Haare",
    "mittellang",
    "Wei\xDFk\xE4ppchen",
    "normal",
    "Spitzhelm",
    "Eisenmaske",
    "Topfhelm",
    "normal",
    "Ritterin",
    "fesch",
    "Augenmaske",
    "Einhorn",
    "Gitterhelm",
    "Knollhelm",
    "Fl\xFCgelhelm",
    "Kreisel",
    "Tulpe",
    "L\xF6" "ffel",
    "Schleife",
    "Wolfkopf",
    "Haiauge",
    "B\xE4rentatze",
    "Otterschwanz",
    "Katzenbein",
    "Otterschwanz",
    "Haiauge",
    "Eulenkopf",
};

char *gLookNames_It[] = {
    "Ciuffo ribelle",
    "Naturale",
    "Fascia",
    "Cappello",
    "Capelli lunghi",
    "Capelli corti",
    "Giacca scura",
    "Cappello",
    "Pettinato",
    "Elmo di corno",
    "Elmo d'acciaio",
    "Secchio",
    "Pettinata",
    "Blu",
    "Elegante",
    "Mascherina",
    "Monocorno",
    "Irregolare",
    "Becco lungo",
    "Mago nero",
    "Spirale",
    "Tulipano",
    "Cucchiaio",
    "Cuore",
    "Lupo",
    "Occhi rapaci",
    "Bandana",
    "Procione",
    "Lupa",
    "Procione",
    "Occhi rapaci",
    "Testa di gufo",
};

char *gLookNames_Fr[] = {
    "Epi",
    "Naturel",
    "Bandeau",
    "Chapeau",
    "Plumes",
    "Brune",
    "Ch\xE2tain",
    "Chapeau",
    "T\xEAte nue",
    "Cornes",
    "Visi\xE8re",
    "Heaume",
    "T\xEAte nue",
    "Heaume",
    "El\xE9gante",
    "Masqu\xE9" "e",
    "Unicorne",
    "Bosses",
    "Long bec",
    "Mage noir",
    "Spirale",
    "Tulipe",
    "Cuill\xE8re",
    "C\x9Cur",
    "Loup",
    "Lynx",
    "Bandana",
    "Castor",
    "Louve",
    "Castor",
    "Lynx",
    "Hibou",
};

char *gLookNames_Es[] = {
    "Remolino",
    "Natural",
    "Cinta",
    "Gorra",
    "Cabello Largo",
    "Cabello Corto",
    "Chaqueta Osc.",
    "Gorro Blanco",
    "Cabeza Aire",
    "Yelmo Cuerno",
    "Visor Met\xE1lico",
    "Cabeza Balde",
    "Cabeza Aire",
    "Azul",
    "Elegante",
    "M\xE1scara Roja",
    "Un Cuerno",
    "Zarandeado",
    "Pico Largo",
    "Magia Negra",
    "Espiral",
    "Tulip\xE1n",
    "Cuchara",
    "Cresta Coraz.",
    "Lobezna",
    "Ojos Tibur\xF3n",
    "Bandana",
    "Cola Mapache",
    "Lobezna",
    "Cola Mapache",
    "Ojos Tibur\xF3n",
    "Cabeza B\xFAho",
};

char *gCMakeText_En[] = {
    "Confirm",
    "Character Name",
    "Select Gender",
    "Select Tribe",
    "",
    "",
    "Select Family Trade",
    "Male",
    "Female",
    "",
    "",
    "",
    "Blacksmith",
    "Tailor",
    "Farmer",
    "Rancher",
    "Miller",
    "Fisherman",
    "Merchant",
    "Alchemist",
    "Proceed?",
    "Start from where?",
    "Yes    No",
    "Name:",
    "Gender:",
    "Tribe:",
    "Family Trade:",
};

char *gCMakeText_De[] = {
    "Best\xE4tigen",
    "Charakter benennen",
    "Geschlecht bestimmen",
    "Rasse bestimmen",
    "",
    "",
    "Elterlichen Beruf w\xE4hlen",
    "M\xE4nnlich",
    "Weiblich",
    "",
    "",
    "",
    "Schmied",
    "Schneider",
    "Bauer",
    "Viehz\xFC" "chter",
    "M\xFCller",
    "Fischer",
    "H\xE4ndler",
    "Alchemist",
    "Weiter?",
    "Was korrigieren?",
    "Ja     Nein",
    "Name:",
    "Geschlecht:",
    "Rasse:",
    "Elterlicher Beruf:",
};

char *gCMakeText_It[] = {
    "Conferma",
    "Nome Personaggio",
    "Sesso Personaggio",
    "Razza",
    "",
    "",
    "Attivit\xE0 Familiare",
    "Maschio",
    "Femmina",
    "",
    "",
    "",
    "Fabbri",
    "Sarti",
    "Agricoltori",
    "Allevatori",
    "Mugnai",
    "Pescatori",
    "Mercanti",
    "Alchimisti",
    "Vuoi procedere?",
    "Da dove riprendi?",
    "S\xEC     No",
    "Nome:",
    "Sesso:",
    "Razza:",
    "Mestiere:",
};

char *gCMakeText_Fr[] = {
    "Confirmer",
    "Nom du personnage",
    "Choix du sexe",
    "Choix de la tribu",
    "",
    "",
    "Profession familiale",
    "Masculin",
    "F\xE9minin",
    "",
    "",
    "",
    "Forgeron",
    "Tailleur",
    "Fermier",
    "\xC9leveur",
    "Meunier",
    "P\xEA" "cheur",
    "Marchand",
    "Alchimiste",
    "Continuer?",
    "Reprendre o\xF9?",
    "Oui    Non",
    "Nom:",
    "Sexe:",
    "Tribu:",
    "M\xE9tier:",
};

char *gCMakeText_Es[] = {
    "Confirmar",
    "Nombre del personaje",
    "Elige sexo.",
    "Escoge tribu.",
    "",
    "",
    "Oficio familiar.",
    "Hombre",
    "Mujer",
    "",
    "",
    "",
    "Herrero",
    "Sastre",
    "Campesino",
    "Granjero",
    "Molinero",
    "Pescador",
    "Comerciante",
    "Alquimista",
    "\xBF" "Continuar?",
    "\xBF" "D\xF3nde comienzas?",
    "S\xED     No",
    "Nombre:",
    "Sexo:",
    "Tribu:",
    "Oficio familiar:",
};

char *gLetterText_En[] = {
    "Take out ",
    "Send item.",
    "\"",
    "\"",
    "Send",
    " the reply:",
    "",
    "Proceed?",
    "the ",
    "Cannot take out",
    "Cannot send.",
    "Send gil.",
    "Send nothing.",
    "Include: ",
};

char *gLetterText_De[] = {
    " herausholen?",
    "Gegenstand beif\xFCgen",
    "\x84",
    "\"",
    "",
    " die Antwort",
    " schicken.",
    "Weiter?",
    " wurde",
    "nicht gefunden.",
    "Brief wurde nicht abgeschickt.",
    "Gil beif\xFCgen",
    "Nichts beif\xFCgen",
    " beif\xFCgen.",
};

char *gLetterText_It[] = {
    "Vuoi prendere ",
    "Invia oggetto.",
    "\"",
    "\"",
    "",
    "Vuoi rispondere a ",
    "con ",
    "Vuoi procedere?",
    "",
    "Impossibile prendere.",
    "Invio non riuscito.",
    "Invia guil.",
    "Non inviare nulla.",
    "Allegato: ",
};

char *gLetterText_Fr[] = {
    "Prendre ",
    "Envoyer un objet",
    "\"",
    "\"",
    " la r\xE9ponse",
    "Envoyer \xE0 ",
    "",
    "Continuer?",
    "",
    "Inventaire plein",
    "Ne peut \xEAtre envoy\xE9",
    "Envoyer des gils",
    "Ne rien envoyer",
    "Joindre: ",
};

char *gLetterText_Es[] = {
    "\xBF" "Extraer ",
    "Enviar objeto",
    "\"",
    "\"",
    ".",
    "Enviar la respuesta a ",
    "",
    "\xBF" "Continuar?",
    "",
    "No puedes extraerlo",
    "No se puede enviar",
    "Enviar guiles",
    "No enviar nada",
    "Incluir: ",
};

#endif
