#include "global.h"

char *gMonsterNames_En[] = {
    "???",
    "Flan",
    "Water Flan",
    "Dark Flan",
    "Bomb",
    "Ice Bomb",
    "Thunder Bomb",
    "Ahriman",
    "Ice Ahriman",
    "Lava Ahriman",
    "Griffin",
    "Cerberus",
    "Ochu",
    "Behemoth",
    "Cactuar",
    "Blazer Beetle",
    "Mu",
    "Snow Mu",
    "Lava Mu",
    "Hedgehog Pie",
    "Dark Hedgehog",
    "Stone Hedgehog",
    "Skeleton",
    "Skeleton",
    "Skeleton",
    "Skeleton Mage",
    "Carrion worm",
    "Tiny Worm",
    "Lizardman",
    "Lizardman",
    "Lizardman",
    "Lizard Mage",
    "Lizard Soldier",
    "Lizard Warrior",
    "Lizard Skirmisher",
    "Lizard Wizard",
    "Gigan Toad",
    "Abaddon",
    "Ghost",
    "Tonberry",
    "Tonberry Chef",
    "Electric Jellyfish",
    "Wraith",
    "Goblin",
    "Goblin",
    "Goblin",
    "Goblin Mage",
    "Goblin Worker",
    "Orc",
    "Orc",
    "Orc",
    "Orc Mage",
    "Ogre",
    "Chimera",
    "Gigas",
    "Coeurl",
    "Zu",
    "Gargoyle",
    "Cockatrice",
    "Lamia",
    "Sahagin",
    "Sand sahagin",
    "Stone sahagin",
    "Sahagin lord",
    "Scorpion",
    "Electric Scorpion",
    "Rock Scorpion",
    "Killer Bee",
    "Killer Bee",
    "Killer Bee",
    "Dark Bee",
    "Bat",
    "Sonic Bat",
    "Vampire Bat",
    "Nightmare",
    "Shade",
    "Shade",
    "Shade",
    "Hell Plant",
    "Magic Plant",
    "Stone Plant",
    "Gremlin",
    "Death Knight",
    "Death Knight",
    "Death Knight",
    "Mimic",
    "Sphere",
    "Tentacle",
    "Tentacle",
    "Tentacle",
    "Tentacle",
    "Giant Crab",
    "Right Claw",
    "Left Claw",
    "Reaver Mu",
    "Malboro",
    "Hell Plant",
    "Magic Plant",
    "Stone Plant",
    "Orc King",
    "Orc Pawn",
    "Orc Pawn",
    "Orc Pawn",
    "Goblin King",
    "Goblin",
    "Goblin",
    "Goblin",
    "Armstrong",
    "Skeleton Mage",
    "Skeleton",
    "Skeleton",
    "Gigas Lord",
    "Maggie",
    "Golem",
    "Water Flan",
    "Lizardman King",
    "Lizard Skirmisher",
    "Lizard Wizard",
    "Coeurl",
    "Cave Worm",
    "Electric Jellyfish",
    "Iron Giant",
    "Goblin Mage",
    "Antlion",
    "Scorpion",
    "Electric Scorpion",
    "Rock Scorpion",
    "Lich",
    "Skeleton",
    "Skeleton",
    "Skeleton",
    "Dragon Zombie",
    "Stone Sahagin",
    "Meteor Parasite",
    "Meteor Parasite",
    "Meteor Parasite",
    "Meteor Parasite",
    "Tentacle",
    "Tentacle",
    "Tentacle",
    "Tentacle",
    "Tentacle",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Parasite Duct",
    "Mio-Raem",
    "Raem",
    "Minion",
    "Urn",
    "Saw",
    "Goblin Chieftain",
    "Carrion Worm",
    "Lizard Captain",
    "Gigas Lord",
    "Orc King",
    "Orc King",
    "Steam",
    "Catapult",
    "Minion",
    "Minion",
    "Monstrous Minion",
    "Cave Worm",
    "Iron Giant",
    "Antlion",
    "Antlion",
    "Lich",
    "Dragon Zombie",
    "Meteor Parasite",
    "Meteor Parasite",
    "Ogre",
    "Skeleton Mage",
    "Gigan Toad",
    "Flan",
    "Mio-Raem",
    "Raem",
    "Skeleton Mage",
    "Skeleton Mage",
    "Skeleton Mage",
    "Goblin King",
    "Goblin King",
    "Lizard Skirmisher",
    "Chimera",
    "Giant Crab",
    "Giant Crab",
    "Malboro",
    "Armstrong",
    "Golem",
    "Golem",
    "Practice Goblin",
};

char *gMonsterNames_De[] = {
    "???",
    "Kampfpudding",
    "Wasserpudding",
    "Teufelspudding",
    "Bomber",
    "Eisbomber",
    "Donnerbomber",
    "Ahriman",
    "Eis-Ahriman",
    "Lava-Ahriman",
    "Gryphon",
    "Zerberus",
    "K\xFCsschen",
    "Behemoth",
    "Kaktor",
    "Einhornk\xE4" "fer",
    "Mu",
    "Schnee-Mu",
    "Lava-Mu",
    "Igelquappe",
    "Teufelsquappe",
    "Steinquappe",
    "Skeleton",
    "Skeleton",
    "Skeleton",
    "Skeleton-Magier",
    "Sihslockawurm",
    "Lockawurm",
    "Echsenmensch",
    "Echsenmensch",
    "Echsenmensch",
    "Echsenmagier",
    "Echsenkrieger",
    "Echsenkrieger",
    "Echsenlandser",
    "Echsenhexer",
    "Karpfenkr\xF6te",
    "Abadon",
    "Schreckgespenst",
    "Tombery",
    "Chefkoch-Tombery",
    "Elektro-Qualle",
    "Todesabt",
    "Goblin",
    "Goblin",
    "Goblin",
    "Goblin-Magus",
    "Goblin-Krieger",
    "Ork",
    "Ork",
    "Ork",
    "Ork-Magier",
    "Oger",
    "Chim\xE4ra",
    "Gigas",
    "Quahl",
    "Montisaurus",
    "Gargoyle",
    "Cockatrice",
    "Lamia",
    "Sahagin",
    "Knochen-Sahagin",
    "Stein-Sahagin",
    "K\xF6nig-Sahagin",
    "Skorpion",
    "Elektro-Skorpion",
    "Granit-Skorpion",
    "Killerbiene",
    "Killerbiene",
    "Killerbiene",
    "Teufelsbiene",
    "Fledermaus",
    "Sonic-Fl\xFCgler",
    "Vampir",
    "H\xF6llenross",
    "Alb",
    "Alb",
    "Alb",
    "Teufelsfarn",
    "Drudenfarn",
    "Steinfarn",
    "Gremlin",
    "Schattenritter",
    "Schattenritter",
    "Schattenritter",
    "Mimik",
    "Schattensph\xE4re",
    "Parasitenspross",
    "Parasitenspross",
    "Parasitenspross",
    "Parasitenspross",
    "Monsterkrabbe",
    "Rechte Klaue",
    "Linke Klaue",
    "Fluss-Mu",
    "Morbol",
    "Teufelsfarn",
    "Drudenfarn",
    "Steinfarn",
    "Ork-K\xF6nig",
    "Ork-Sklave",
    "Ork-Sklave",
    "Ork-Sklave",
    "Goblin-K\xF6nig",
    "Goblin",
    "Goblin",
    "Goblin",
    "Hausmann",
    "Skeleton-Magier",
    "Skeleton",
    "Skeleton",
    "Lord Gigas",
    "Frau Moschet",
    "Golem",
    "Wasserpudding",
    "Echsenk\xF6nig",
    "Echsenlandser",
    "Echsenhexer",
    "Quahl",
    "Grottenwurm",
    "Elektro-Qualle",
    "Eisengigant",
    "Goblin-Magus",
    "Ameisenl\xF6we",
    "Skorpion",
    "Elektro-Skorpion",
    "Granit-Skorpion",
    "Todbringer",
    "Skeleton",
    "Skeleton",
    "Skeleton",
    "Drachenzombie",
    "Stein-Sahagin",
    "Meteo-Parasit",
    "Meteo-Parasit",
    "Meteo-Parasit",
    "Meteo-Parasit",
    "Parasitenspross",
    "Parasitenspross",
    "Parasitenspross",
    "Parasitenspross",
    "Parasitenspross",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Parasitenk\xF6rper",
    "Mio-Raem",
    "Raem",
    "Teufelsbote",
    "Urne",
    "Kreiss\xE4ge",
    "Goblin-Meister",
    "Sihslockawurm",
    "General Echse",
    "Lord Gigas",
    "Ork-K\xF6nig",
    "Ork-K\xF6nig",
    "Dampf",
    "Katapult",
    "Teufelsbote",
    "Teufelsbote",
    "Schattenbote",
    "Grottenwurm",
    "Eisengigant",
    "Ameisenl\xF6we",
    "Ameisenl\xF6we",
    "Todbringer",
    "Drachenzombie",
    "Meteo-Parasit",
    "Meteo-Parasit",
    "Oger",
    "Skeleton-Magier",
    "Karpfenkr\xF6te",
    "Kampfpudding",
    "Mio-Raem",
    "Raem",
    "Skeleton-Magier",
    "Skeleton-Magier",
    "Skeleton-Magier",
    "Goblin-K\xF6nig",
    "Goblin-K\xF6nig",
    "Echsenlandser",
    "Chim\xE4ra",
    "Monsterkrabbe",
    "Monsterkrabbe",
    "Morbol",
    "Hausmann",
    "Golem",
    "Golem",
    "Trainings-Goblin",
};

char *gMonsterNames_It[] = {
    "???",
    "Budino",
    "Idrobudino",
    "Budino oscuro",
    "Piros",
    "Piros gelo",
    "Piros tuono",
    "Alyman",
    "Alyman gelo",
    "Alyman lavico",
    "Grifone",
    "Cerbero",
    "Ochu",
    "Behemoth",
    "Kyactus",
    "Insetto ardente",
    "Mu",
    "Mu di neve",
    "Mu lavico",
    "Istrice",
    "Istrice oscuro",
    "Istrice pietroso",
    "Scheletro",
    "Scheletro",
    "Scheletro",
    "Schelemago",
    "Necroverme",
    "Vermicello",
    "Reptiuomo",
    "Reptiuomo",
    "Reptiuomo",
    "Reptimago",
    "Reptisoldato",
    "Reptimilite",
    "Reptiribelle",
    "Reptistregone",
    "Rospo gigante",
    "Abaddon",
    "Fantasma",
    "Tomberry",
    "Chef tomberry",
    "Elettromedusa",
    "Spettro",
    "Goblin",
    "Goblin",
    "Goblin",
    "Mago goblin",
    "Operaio goblin",
    "Orco",
    "Orco",
    "Orco",
    "Orco mago",
    "Babau",
    "Chimera",
    "Giga",
    "Iaguaro",
    "Zuu",
    "Gargolla",
    "Basilisco",
    "Lamia",
    "Sahagin",
    "Sahagin renoso",
    "Sahagin pietroso",
    "Lord sahagin",
    "Scorpione",
    "Elettroscorpione",
    "Scorpione roccioso",
    "Ape assassina",
    "Ape assassina",
    "Ape assassina",
    "Ape oscura",
    "Nottola",
    "Nottola sonica",
    "Vampiro",
    "Incubo",
    "Ombra",
    "Ombra",
    "Ombra",
    "Pianta invasata",
    "Pianta magica",
    "Pianta pietrosa",
    "Folletto",
    "Ultimo cavaliere",
    "Ultimo cavaliere",
    "Ultimo cavaliere",
    "Mimik",
    "Sfera",
    "Tentacolo",
    "Tentacolo",
    "Tentacolo",
    "Tentacolo",
    "Granchio gigante",
    "Artiglio destro",
    "Artiglio sinistro",
    "Mu predatore",
    "Molboro",
    "Pianta invasata",
    "Pianta magica",
    "Pianta pietrosa",
    "Re degli orchi",
    "Recluta orco",
    "Recluta orco",
    "Recluta orco",
    "Re dei goblin",
    "Goblin",
    "Goblin",
    "Goblin",
    "Malabraccio",
    "Schelemago",
    "Scheletro",
    "Scheletro",
    "Lord Giga",
    "Maggie",
    "Golem",
    "Idrobudino",
    "Reptire",
    "Reptiribelle",
    "Reptistregone",
    "Iaguaro",
    "Atroverme",
    "Elettromedusa",
    "Gigante ferreo",
    "Mago goblin",
    "Antoleon",
    "Scorpione",
    "Elettroscorpione",
    "Scorpione roccioso",
    "Cadavere",
    "Scheletro",
    "Scheletro",
    "Scheletro",
    "Drago zombie",
    "Sahagin pietroso",
    "Meteossita",
    "Meteossita",
    "Meteossita",
    "Meteossita",
    "Tentacolo",
    "Tentacolo",
    "Tentacolo",
    "Tentacolo",
    "Tentacolo",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Parassidotto",
    "Mio Raem",
    "Raem",
    "Servo",
    "Urna",
    "Sega",
    "Capo goblin",
    "Necroverme",
    "Repticapitano",
    "Lord Giga",
    "Re degli orchi",
    "Re degli orchi",
    "Vapore",
    "Catapulta",
    "Servo",
    "Servo",
    "Servo mostruoso",
    "Atroverme",
    "Gigante ferreo",
    "Antoleon",
    "Antoleon",
    "Cadavere",
    "Drago zombie",
    "Meteossita",
    "Meteossita",
    "Babau",
    "Schelemago",
    "Rospo gigante",
    "Budino",
    "Mio Raem",
    "Raem",
    "Schelemago",
    "Schelemago",
    "Schelemago",
    "Re dei goblin",
    "Re dei goblin",
    "Reptiribelle",
    "Chimera",
    "Granchio gigante",
    "Granchio gigante",
    "Molboro",
    "Malabraccio",
    "Golem",
    "Golem",
    "Istruttore goblin",
};

char *gMonsterNames_Fr[] = {
    "???",
    "Flambos",
    "Flambos d'eau",
    "Flambos noir",
    "Bombo",
    "Bombo de glace",
    "Bombo de tonnerre",
    "Ahriman",
    "Ahriman de glace",
    "Ahriman de lave",
    "Griffon",
    "Cerb\xE8re",
    "Ochu",
    "B\xE9h\xE9moth",
    "Pampa",
    "Ateuchus",
    "Eskuriax",
    "Eskuriax de neige",
    "Eskuriax de lave",
    "T\xE9tarosor",
    "T\xE9tarosor noir",
    "T\xE9tarosor de pierre",
    "Squelette",
    "Squelette",
    "Squelette",
    "Squelettomage",
    "Pyrale",
    "Vermisseau",
    "Ka\xEFmahn",
    "Ka\xEFmahn",
    "Ka\xEFmahn",
    "Ka\xEFmage",
    "Soldat ka\xEFmahn",
    "Guerrier ka\xEFmahn",
    "L\xE9gionnaire ka\xEFmahn",
    "Sorcier ka\xEFmahn",
    "Crapaud-buffle",
    "Abadon",
    "Fant\xF4me",
    "Tomberry",
    "Chef tomberry",
    "Electro-m\xE9" "duse",
    "Spectre",
    "Gobelin",
    "Gobelin",
    "Gobelin",
    "Gobelimage",
    "Gobelitravailleur",
    "Orc",
    "Orc",
    "Orc",
    "Orc-mage",
    "Ogre",
    "Chimaira",
    "Gigas",
    "coeurl",
    "Zu",
    "Gargouille",
    "Gallus",
    "Lamia",
    "Sahuagin",
    "Sahuagin des sables",
    "Sahuagin de pierre",
    "Seigneur sahuagin",
    "Scorpion",
    "Scorpion \xE9lectrique",
    "P\xE9trascorpion",
    "Abeille tueuse",
    "Abeille tueuse",
    "Abeille tueuse",
    "Abeille noire",
    "Chauve-souris",
    "Chauve-souris sonique",
    "Chauve-souris vampire",
    "Cauchemar",
    "Ombre",
    "Ombre",
    "Ombre",
    "Plante infernale",
    "Plante magique",
    "P\xE9traplante",
    "Diablotin",
    "Chevalier de la Mort",
    "Chevalier de la Mort",
    "Chevalier de la Mort",
    "Mimic",
    "Sph\xE8re",
    "Tentacule",
    "Tentacule",
    "Tentacule",
    "Tentacule",
    "M\xE9gacrabe",
    "Pince droite",
    "Pince gauche",
    "Eskuriax ravageur",
    "Xylomid",
    "Plante infernale",
    "Plante magique",
    "P\xE9traplante",
    "Roi orc",
    "Laquais orc",
    "Laquais orc",
    "Laquais orc",
    "Roi gobelin",
    "Gobelin",
    "Gobelin",
    "Gobelin",
    "Bertha",
    "Squelettomage",
    "Squelette",
    "Squelette",
    "Seigneur Gigas",
    "Maggie",
    "Golem",
    "Flambos d'eau",
    "Roi Ka\xEFmahn",
    "L\xE9gionnaire ka\xEFmahn",
    "Sorcier ka\xEFmahn",
    "Couguar",
    "Ver des Cavernes",
    "Electro-m\xE9" "duse",
    "Ekarissor",
    "Gobelimage",
    "Fourmilion",
    "Scorpion",
    "Scorpion \xE9lectrique",
    "P\xE9trascorpion",
    "Kaozium",
    "Squelette",
    "Squelette",
    "Squelette",
    "Dragon Zombie",
    "P\xE9trasahuagin",
    "M\xE9t\xE9o-parasite",
    "M\xE9t\xE9o-parasite",
    "M\xE9t\xE9o-parasite",
    "M\xE9t\xE9o-parasite",
    "Tentacule",
    "Tentacule",
    "Tentacule",
    "Tentacule",
    "Tentacule",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Conduit parasite",
    "Mioraem",
    "Raem",
    "Laquais",
    "Urne",
    "Scie",
    "Chef gobelin",
    "Pyrale",
    "Capitaine ka\xEFmahn",
    "Seigneur Gigas",
    "Roi orc",
    "Roi orc",
    "Vapeur",
    "Catapulte",
    "Sous-fifre",
    "Sous-fifre",
    "Sous-fifre",
    "Ver des Cavernes",
    "Ekarissor",
    "Fourmilion",
    "Fourmilion",
    "Kaozium",
    "Dragon Zombie",
    "M\xE9t\xE9o-parasite",
    "M\xE9t\xE9o-parasite",
    "Ogre",
    "Squelettomage",
    "Crapaud-buffle",
    "flambos",
    "Mioraem",
    "Raem",
    "Squelettomage",
    "Squelettomage",
    "Squelettomage",
    "Roi gobelin",
    "Roi gobelin",
    "L\xE9gionnaire ka\xEFmahn",
    "Chimaira",
    "M\xE9gacrabe",
    "M\xE9gacrabe",
    "Xylomid",
    "Bertha",
    "Golem",
    "Golem",
    "Gobelin d'entra\xEEnement",
};

char *gMonsterNames_Es[] = {
    "\xBF\xBF??",
    "Flan",
    "Flan de agua",
    "Flan oscuro",
    "Bomba",
    "Bomba de hielo",
    "Bomba electro",
    "Arim\xE1n",
    "Arim\xE1n hielo",
    "Arim\xE1n lava",
    "Grifo",
    "Cerbero",
    "Ochu",
    "B\xE9gimo",
    "Cactilio",
    "Aracornio",
    "Mu",
    "Mu de nieve",
    "Mu de lava",
    "Esp\xEDn",
    "Barrera oscura",
    "Barrera piedra",
    "Esqueleto",
    "Esqueleto",
    "Esqueleto",
    "Esquelet. mago",
    "Oruga",
    "Oruga peque\xF1" "a",
    "Hombre reptil",
    "Hombre reptil",
    "Hombre reptil",
    "Reptil mago",
    "Reptil soldado",
    "Rept. guerrero",
    "Rept. peleador",
    "Reptil druida",
    "Sapo gigante",
    "Abad\xF3n",
    "Fantasma",
    "Tomberi",
    "Cocinero tomb.",
    "Medusa el\xE9" "c.",
    "Caronte",
    "Duende",
    "Duende",
    "Duende",
    "Duende mago",
    "Duende trabaj.",
    "Orco",
    "Orco",
    "Orco",
    "Orco mago",
    "Ogro",
    "Quimera",
    "Gigas",
    "Bengal",
    "Zu",
    "G\xE1rgola",
    "Cocatoris",
    "Lamia",
    "Gurami",
    "Gurami arena",
    "Gurami piedra",
    "Se\xF1or gurami",
    "Escorpio",
    "Escorpio el\xE9" "c.",
    "Escorpio roca",
    "Abeja asesina",
    "Abeja asesina",
    "Abeja asesina",
    "Abeja oscura",
    "Murci\xE9lago",
    "Murci\xE9. s\xF3nic.",
    "Vampiro",
    "Pesadilla",
    "Sombra",
    "Sombra",
    "Sombra",
    "Planta inferno",
    "Planta m\xE1gica",
    "Planta piedra",
    "Gremlin",
    "Caball. muerte",
    "Caball. muerte",
    "Caball. muerte",
    "M\xEDmico",
    "Esfera",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Cangrejo Gig.",
    "Garra derecha",
    "Garra izquier.",
    "Mu marchoso",
    "Molbol",
    "Planta inferno",
    "Planta m\xE1gica",
    "Planta piedra",
    "Rey Orco",
    "Orco pe\xF3n",
    "Orco pe\xF3n",
    "Orco pe\xF3n",
    "Rey Duende",
    "Duende",
    "Duende",
    "Duende",
    "Armstrong",
    "Esquelet. mago",
    "Esqueleto",
    "Esqueleto",
    "Gran Gigas",
    "Marga",
    "G\xF3lem",
    "Flan de agua",
    "Rey Reptil ",
    "Rept. peleador",
    "Reptil druida",
    "Bengal",
    "Gusano de Cav.",
    "Medusa el\xE9" "c.",
    "F\xE9rreo",
    "Duende mago",
    "Antole\xF3n",
    "Escorpio",
    "Escorpio el\xE9" "c.",
    "Escorpio roca",
    "Lich",
    "Esqueleto",
    "Esqueleto",
    "Esqueleto",
    "Drag\xF3n Zombi",
    "Gurami piedra",
    "Par\xE1sito Met.",
    "Par\xE1sito Met.",
    "Par\xE1sito Met.",
    "Par\xE1sito Met.",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Tent\xE1" "culo",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Tubo par\xE1sito",
    "Mio-Raem",
    "Raem",
    "Mi\xF1\xF3n",
    "Urna",
    "Sierra",
    "Duende cacique",
    "Oruga",
    "Reptil capit\xE1n",
    "Gran Gigas",
    "Rey Orco",
    "Rey Orco",
    "Vapor",
    "Catapulta",
    "Mi\xF1\xF3n",
    "Mi\xF1\xF3n",
    "Mi\xF1\xF3n monst.",
    "Gusano de Cav.",
    "F\xE9rreo",
    "Antole\xF3n",
    "Antole\xF3n",
    "Lich",
    "Drag\xF3n Zombi",
    "Par\xE1sito Met.",
    "Par\xE1sito Met.",
    "Ogro",
    "Esquelet. mago",
    "Sapo gigante",
    "Flan",
    "Mio-Raem",
    "Raem",
    "Esquelet. mago",
    "Esquelet. mago",
    "Esquelet. mago",
    "Rey Duende",
    "Rey Duende",
    "Rept. peleador",
    "Quimera",
    "Cangrejo Gig.",
    "Cangrejo Gig.",
    "Molbol",
    "Armstrong",
    "G\xF3lem",
    "G\xF3lem",
    "Duende pr\xE1" "ct.",
};
