#include "global.h"

char *gItemNames_En[] = {
    "DUMMY-UK",
    "Copper Sword",
    "Iron Sword",
    "Steel Blade",
    "Feather Sabre",
    "Bastard Sword",
    "Defender",
    "Rune Blade",
    "Excalibur",
    "Ragnarok",
    "Treas. Sword",
    "Fthr. Sword",
    "Marr Sword",
    "Test 1",
    "Test 2",
    "Ultima Sword",
    "Equip. 116",
    "Equip. 117",
    "Iron Lance",
    "Partisan",
    "Sonic Lance",
    "Titan Lance",
    "Halberd",
    "Highwind",
    "Dragon Lance",
    "Dragoon Spear",
    "Gungnir",
    "Longinus",
    "Treas. Spear",
    "Fthr. Spear",
    "Marr Spear",
    "Ultima Lance",
    "Equip. 119",
    "Equip. 120",
    "Equip. 121",
    "Equip. 122",
    "Orc Hammer",
    "Wave Hammer",
    "Rune Hammer",
    "Goblin Hammer",
    "Sonic Hammer",
    "Prism Hammer",
    "Mythril Hammer",
    "Mystic Hammer",
    "Treas. Hammer",
    "Fthr. Hammer",
    "Marr Hammer",
    "Ultima Hammer",
    "Equip. 124",
    "Equip. 125",
    "Equip. 126",
    "Equip. 127",
    "Aura Racket",
    "Solid Racket",
    "Dual Shooter",
    "Elemnt. Cudgel",
    "Steel Cudgel",
    "Prism Bludgeon",
    "Butterfly Head",
    "Queen's Heel",
    "Drmcatcher.",
    "Treas. Maul",
    "Fthr. Maul",
    "Marr Maul",
    "Ultima Maul",
    "Equip. 129",
    "Equip. 130",
    "Equip. 131",
    "Equip. 132",
    "Travel Clothes",
    "Bronze Plate",
    "Iron Plate",
    "Mythril Plate",
    "Flame Mail",
    "Frost Mail",
    "Storm Mail",
    "Time Mail",
    "Eternal Mail",
    "Blessed Mail",
    "Saintly Mail",
    "Gold Mail",
    "Crystal Mail",
    "Diamond Plate",
    "Gaia Plate",
    "Mystic Armour",
    "Ttrskn. Coat",
    "Coat",
    "Baggy Coat",
    "Makeshift Shd.",
    "Iron Shield",
    "Mythril Shield",
    "Flame Shield",
    "Frost Shield",
    "Storm Shield",
    "Saintly Shield",
    "Diamond Shield",
    "Rune Shield",
    "Chocobo Shield",
    "Gauntlets",
    "Bronze Gntls.",
    "Iron Gntls.",
    "Mythril Gntls.",
    "Flame Armlets",
    "Frost Armlets",
    "Storm Armlets",
    "Gold Armlets",
    "Diamond Arms.",
    "Helm",
    "Bronze Helm",
    "Iron Helm",
    "Mythril Helm",
    "Flame Helm",
    "Frost Helm",
    "Storm Helm",
    "Time Helm",
    "Eternal Helm",
    "Diamond Helm",
    "Old Belt",
    "Bronze Belt",
    "Iron Belt",
    "Mythril Belt",
    "Flame Sash",
    "Frost Sash",
    "Storm Sash",
    "Blessed Sash",
    "Winged Belt",
    "Diamond Belt",
    "Flame Badge",
    "Frost Badge",
    "Thunder Badge",
    "Acc. Watch",
    "Unfalt. Watch",
    "Blue Misanga",
    "White Misanga",
    "Gold Necklace",
    "Wisdom Charm",
    "Wisdom Talsmn.",
    "Flower Bracer",
    "Speed Charm",
    "Speed Tlsmn.",
    "Thief's Emblem",
    "Zeal Headband",
    "Dmn. Earring",
    "Devil's Earring",
    "Pixie's Earring",
    "Angel's Earring",
    "Crystal Ring",
    "Twisted Spect.",
    "Twisted Scope",
    "Healing Hdbnd.",
    "Jade Bracer",
    "Power Goggles",
    "Eagle Goggles",
    "Lion's Heart",
    "Dragon Heart",
    "Wizard's Soul",
    "Bishop's Soul",
    "Elemental Soul",
    "Force Ring",
    "Shuriken",
    "Maneater",
    "Double Axe",
    "Ashura",
    "Kaiser Knckls.",
    "Flametongue",
    "Ice Brand",
    "Loaded Dice",
    "Ogrekiller",
    "Engetsurin",
    "Sasuke Blade",
    "Mj\xF6llnir",
    "Masquerade",
    "Murasame",
    "Masamune",
    "Gekkabijin",
    "Onion Sword",
    "Power Wrist.",
    "Green Beret",
    "Fang Charm",
    "Twist. Hdbnd.",
    "Heavy Armbnd.",
    "Giant's Glove",
    "Drgn. Whisker",
    "Mage Masher",
    "Rune Staff",
    "Book of Light",
    "Sage's Staff",
    "Wonder Wand",
    "Rune Bell",
    "Mage's Staff",
    "Noah's Lute",
    "Galatyn",
    "Ultima Tome",
    "Silver Bracer",
    "Cat's Bell",
    "Faerie Ring",
    "Winged Cap",
    "Candy Ring",
    "Kris",
    "Red Slippers",
    "Dark Matter",
    "Gold Hairpin",
    "Taotie Motif",
    "Ribbon",
    "Main Gauche",
    "Chicken Knife",
    "Save Queen",
    "Drill",
    "Buckler",
    "Silver Spect.",
    "Spark. Bracer",
    "Black Hood",
    "Arai Helm",
    "Elvan Mantle",
    "Wonder Bangle",
    "Protection Ring",
    "Aegis",
    "Rat's Tail",
    "Teddy Bear",
    "Moogle Pocket",
    "Chocobo Pock.",
    "Gobbie Pocket",
    "Ultimate Pock.",
    "Fire Ring",
    "Blizzard Ring",
    "Thunder Ring",
    "Cure Ring",
    "Life Ring",
    "Earth Pendant",
    "Moon Pendant",
    "Star Pendant",
    "Sun Pendant",
    "Equip. 187",
    "Equip. 188",
    "Equip. 189",
    "Equip. 190",
    "Equip. 191",
    "Equip. 192",
    "Equip. 193",
    "Equip. 194",
    "Equip. 195",
    "Equip. 196",
    "Equip. 197",
    "Equip. 198",
    "Equip. 199",
    "Equip. 200",
    "Equip. 201",
    "Equip. 202",
    "Equip. 203",
    "Equip. 204",
    "Equip. 205",
    "Equip. 206",
    "Equip. 207",
    "Equip. 208",
    "Equip. 209",
    "Equip. 210",
    "Fire",
    "Blizzard",
    "Thunder",
    "???",
    "Slow",
    "Cure",
    "Clear",
    "Life",
    "Holy",
    "Stop",
    "Gravity",
    "Curse",
    "Illness",
    "Magic Circle",
    "Ultima",
    "Flare",
    "Meteor",
    "Darkness",
    "Zeal",
    "Seize",
    "Confuse",
    "Whirlwind",
    "Examine",
    "Threaten",
    "Favourites",
    "Dice",
    "Blame",
    "Rule",
    "All",
    "Fan",
    "Circle",
    "Trail",
    "Enhance",
    "Double",
    "Add",
    "Reflect",
    "Barrier",
    "Phoenix Down",
    "Bronze",
    "Iron",
    "Mythril",
    "Orichalcum",
    "Diamond Ore",
    "Gold",
    "Silver",
    "Bronze Shard",
    "Iron Shard",
    "Tiny Crystal",
    "Crystal Ball",
    "Ruby",
    "Jade",
    "Alloy",
    "Magma Rock",
    "Chilly Gel",
    "Thunderball",
    "Holy Water",
    "Heavenly Dust",
    "Yellow Feather",
    "Blue Silk",
    "White Silk",
    "Fiend's Claw",
    "Devil's Claw",
    "Faerie's Tear",
    "Angel's Tear",
    "Ancient Sword",
    "Cursed Crook",
    "Orc Belt",
    "King's Scale",
    "Green Sphere",
    "Dragon's Fang",
    "Malboro Seed",
    "Desert Fang",
    "Wind Crystal",
    "Ethereal Orb",
    "Red Eye",
    "Dweomer Spore",
    "Lord's Robe",
    "Griffin's Wing",
    "Cerberus Fang",
    "Needle",
    "Hard Shell",
    "Worm Antenna",
    "Toad Oil",
    "Jagged Scythe",
    "Ogre Fang",
    "Chimera's Horn",
    "Crop Seed",
    "Coeurl Whisker",
    "Zu's Beak",
    "Cockat. Scale",
    "Ancient Potion",
    "Shiny Shard",
    "Gigas Claw",
    "Gear",
    "Pressed Flower",
    "Remedy",
    "Goddess Stat.",
    "Devil's Mask",
    "Extra 22",
    "Flower Seed",
    "Strange Seed",
    "Fruit Seed",
    "Fruit Seed",
    "Fruit Seed",
    "Veg. Seed",
    "Veg. Seed",
    "Veg. Seed",
    "Wheat Seed",
    "Worn Bandana",
    "Shella Mark",
    "Kilanda Sulphur",
    "Cactus Flower",
    "Extra 23",
    "Ultimite",
    "Dark Sphere",
    "Extra 24",
    "Extra 25",
    "Extra 26",
    "Extra 27",
    "Extra 28",
    "Extra 29",
    "Extra 30",
    "Extra 31",
    "Extra 32",
    "Extra 33",
    "Striped Apple",
    "Cherry Cluster",
    "Rainbow Grps.",
    "Star Carrot",
    "Grd. Potato",
    "Round Corn",
    "Meat",
    "Fish",
    "Bannock",
    "Spring Water",
    "Milk",
    "Strange Liquid",
    "Flame Shard",
    "Water Shard",
    "Lightn. Shard",
    "Dark. Shard",
    "Wheat",
    "Flour",
    "???",
    "Item Gil",
    "Novice's Wpn.",
    "Warrior's Wpn.",
    "Valiant Wpn.",
    "Mighty Wpn.",
    "Victorious Wpn.",
    "Master's Wpn.",
    "Legend. Wpn.",
    "Hero's Wpn.",
    "Celestial Wpn.",
    "Dark Wpn.",
    "Lunar Wpn.",
    "Bronze Armour",
    "Iron Armour",
    "Mythril Armour",
    "Flame Armour",
    "Frost Armour",
    "Lightning Armr.",
    "Time Armour",
    "Eternal Armour",
    "Pure Armour",
    "Holy Armour",
    "Gold Armour",
    "Radiant Armour",
    "Diamond Armr.",
    "Earth Armour",
    "Iron Shield",
    "Mythril Shield",
    "Flame Shield",
    "Frost Shield",
    "Lightning Shd.",
    "Holy Shield",
    "Diamond Shield",
    "Magic Shield",
    "Legend. Shield",
    "Bronze Glvs.",
    "Iron Glvs.",
    "Mythril Glvs.",
    "Flame Glvs.",
    "Frost Glvs.",
    "Lightning Glvs.",
    "Gold Glvs.",
    "Diamond Glvs.",
    "Bronze Sallet",
    "Iron Sallet",
    "Mythril Sallet",
    "Flame Sallet",
    "Frost Sallet",
    "Lightn. Sallet",
    "Time Sallet",
    "Eternal Sallet",
    "Diamond Sallet",
    "Bronze Belt",
    "Iron Belt",
    "Mythril Belt",
    "Flame Belt",
    "Frost Belt",
    "Lightning Belt",
    "Pure Belt",
    "Wind Belt",
    "Diamond Belt",
    "Flame Craft",
    "Frost Craft",
    "Lightn. Craft",
    "Clockwork",
    "New Clockwork",
    "Blue Yarn",
    "White Yarn",
    "Gold Craft",
    "Wisdom Tome",
    "Wisd. Secrets",
    "Ladies' Acces.",
    "Speed Tome",
    "Speed Secrets",
    "Brigandology",
    "Zeal Kit",
    "Fiend Kit",
    "Daemon Kit",
    "Faerie Kit",
    "Angel Kit",
    "Ring of Light",
    "Eyewear Tech.",
    "Desnr. Glasses",
    "Healing Kit",
    "Fashion Kit",
    "Goggle Tech.",
    "Desnr. Goggles",
    "Lion Soul",
    "Dragon Soul",
    "Magic Tome",
    "Sorcery Tome",
    "Forbid. Tome",
    "Greatest Wpn.",
    "Ring of Invin.",
    "design 94",
    "design 95",
    "design 96",
    "design 97",
    "design 98",
    "design 99",
    "design 100",
};

char *gItemNames_De[] = {
    "Dummy",
    "Leichtschwert",
    "Eisenschwert",
    "Schutzschwert",
    "Federschwert",
    "Bastard-Schw.",
    "Defendor",
    "Runenschwert",
    "Exkalibur",
    "Ragnar\xF6k",
    "Prunkschwert",
    "Papas Schwert",
    "Marl-Schwert",
    "Test 1",
    "Test 2",
    "Ultima-Schwert",
    "DUMMY 116",
    "DUMMY 117",
    "Eisenlanze",
    "Partisane",
    "Sonic-Lanze",
    "Titan-Lanze",
    "Hellebarde",
    "Highwind",
    "Drachenspeer",
    "Dragonerspeer",
    "Gungnir",
    "Longinus",
    "Prunkspeer",
    "Papas Speer",
    "Marl-Speer",
    "Ultima-Lanze",
    "DUMMY 119",
    "DUMMY 120",
    "DUMMY 121",
    "DUMMY 122",
    "Oger-Hammer",
    "Schlaghammer",
    "Runenhammer",
    "Goblin-Hammer",
    "Sonic-Hammer",
    "Prisma-Hammer",
    "Mithril-Hammer",
    "Zauberhammer",
    "Prunkhammer",
    "Papas Hammer",
    "Marl-Hammer",
    "Ultima-Hammer",
    "DUMMY 124",
    "DUMMY 125",
    "DUMMY 126",
    "DUMMY 127",
    "Aura-Keule",
    "Schlagkeule",
    "Doppelkopf",
    "Elementkeule",
    "Schmetterkeule",
    "Prisma-Keule",
    "Falterkeule",
    "K\xF6nigskeule",
    "Sch\xFCtzenk\xF6nig",
    "Prunkkeule",
    "Papas Keule",
    "Marl-Keule",
    "Ultima-Keule",
    "DUMMY 129",
    "DUMMY 130",
    "DUMMY 131",
    "DUMMY 132",
    "Reisekluft",
    "Bronzer\xFCstung",
    "Eisenr\xFCstung",
    "Mithril-R\xFCst.",
    "Feuerr\xFCstung",
    "Eisr\xFCstung",
    "Donnerr\xFCstung",
    "Chrono-R\xFCst.",
    "\xC4on-R\xFCstung",
    "Sakral-R\xFCst.",
    "Heiligenr\xFCst.",
    "Goldr\xFCstung",
    "Kristallr\xFCst.",
    "Diamantr\xFCst.",
    "Gaia-R\xFCstung",
    "Wunderr\xFCstung",
    "Kartoffeljacke",
    "Reisemantel",
    "Riesenmantel",
    "Holzschild",
    "Eisenschild",
    "Mithril-Schild",
    "Feuerschild",
    "Eisschild",
    "Donnerschild",
    "Heiligenschild",
    "Diamantschild",
    "Runenschild",
    "Choco-Schild",
    "Handschuh",
    "Bronzehands.",
    "Eisenhands.",
    "Mithril-Hands.",
    "Feuerhands.",
    "Eishandschuh",
    "Donnerhands.",
    "Goldhandschuh",
    "Diamanthands.",
    "Helm",
    "Bronzehelm",
    "Eisenhelm",
    "Mithril-Helm",
    "Feuerhelm",
    "Eishelm",
    "Donnerhelm",
    "Chrono-Helm",
    "\xC4on-Helm",
    "Diamanthelm",
    "G\xFCrtel",
    "Bronzeg\xFCrtel",
    "Eiseng\xFCrtel",
    "Mithril-G\xFCrtel",
    "Feuerg\xFCrtel",
    "Eisg\xFCrtel",
    "Donnerg\xFCrtel",
    "Sakral-G\xFCrtel",
    "Fl\xFCgelg\xFCrtel",
    "Diamantg\xFCrtel",
    "Feuerbrosche",
    "Eisbrosche",
    "Donnerbrosche",
    "Taschenuhr",
    "Stoppuhr",
    "Blaue Schleife",
    "Wei\xDF" "e Schleife",
    "Goldkette",
    "Talisman",
    "Amulett",
    "Blumenreif",
    "Falkenkralle",
    "Adlerkralle",
    "R\xE4uberwappen",
    "Stirnband",
    "D\xE4monenring",
    "Teufelsring",
    "Elfenring",
    "Uriel-Ring",
    "Kristallring",
    "Hornbrille",
    "Binokel",
    "Schal",
    "Jadereif",
    "Fernbrille",
    "Fernrohr",
    "L\xF6wenherz",
    "Drachenherz",
    "Magierseele",
    "Klerikerseele",
    "Elementseele",
    "Massivring",
    "Shuriken",
    "Streithammel",
    "Kinnhaken",
    "Asura",
    "Kaiserklaue",
    "Feuerzunge",
    "Schneestern",
    "Zockerw\xFCrfel",
    "Oger-J\xE4ger",
    "Mondreif",
    "Katana",
    "Mj\xF6llnir",
    "Maskerade",
    "Kusanagi",
    "Masamune",
    "Pitaya",
    "Zwiebelklinge",
    "St\xE4rkereif",
    "Baskenm\xFCtze",
    "Rei\xDFzahn",
    "Kopftuch",
    "Sch\xE4rpe",
    "H\xFCnenreif",
    "Drachenj\xE4ger",
    "Krummjuwel",
    "Runenstab",
    "Heiligenbuch",
    "Weisenstab",
    "Wunderrute",
    "Runenglocke",
    "Zauberstab",
    "Noahs Laute",
    "Galatina",
    "Ultima-Skript",
    "Silberreif",
    "Katzenglocke",
    "Elfenwappen",
    "Federhut",
    "Schnuller",
    "Kris",
    "Rote Schuhe",
    "Dunkelopal",
    "Haarnadel",
    "Drudenfu\xDF",
    "Schleife",
    "Dolch",
    "S\xE4" "bel",
    "Tomahawk",
    "Bohrer",
    "Buckler",
    "Goldbrille",
    "Edelreif",
    "Stoffm\xFCtze",
    "Platinhelm",
    "Elfengewand",
    "Wunderreif",
    "Schutzring",
    "Aegis-Ring",
    "Rattenkralle",
    "Teddy",
    "Mog-Tasche",
    "Choco-T.",
    "Goblin-Tasche",
    "Extratasche",
    "Feuer-Ring",
    "Eis-Ring",
    "Blitz-Ring",
    "Vita-Ring",
    "Engel-Ring",
    "Erd-Emblem",
    "Mond-Emblem",
    "Stern-Emblem",
    "Sonnen-Emblem",
    "DUMMY 187",
    "DUMMY 188",
    "DUMMY 189",
    "DUMMY 190",
    "DUMMY 191",
    "DUMMY 192",
    "DUMMY 193",
    "DUMMY 194",
    "DUMMY 195",
    "DUMMY 196",
    "DUMMY 197",
    "DUMMY 198",
    "DUMMY 199",
    "DUMMY 200",
    "DUMMY 201",
    "DUMMY 202",
    "DUMMY 203",
    "DUMMY 204",
    "DUMMY 205",
    "DUMMY 206",
    "DUMMY 207",
    "DUMMY 208",
    "DUMMY 209",
    "DUMMY 210",
    "Feuer",
    "Eis",
    "Blitz",
    "???",
    "Gemach",
    "Vita",
    "Sanitas",
    "Engel",
    "Sanctus",
    "Stopp",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "Ph\xF6nixfeder",
    "Bronze",
    "Eisen",
    "Mithril",
    "Orichalcum",
    "Rohdiamant",
    "Gold",
    "Silber",
    "Bronzesplitter",
    "Eisensplitter",
    "Mini-Kristall",
    "Glaskugel",
    "Rubin",
    "Jade",
    "Edelstein",
    "Magmastein",
    "G\xF6tterspeise",
    "Donnerkugel",
    "Weihwasser",
    "Engelsstaub",
    "Gelbe Feder",
    "Blaue Seide",
    "Wei\xDF" "e Seide",
    "D\xE4monenkralle",
    "Satanskralle",
    "Elfentr\xE4ne",
    "Engelstr\xE4ne",
    "Rostschwert",
    "Hexenstab",
    "Ork-Schnalle",
    "K\xF6nigsschuppe",
    "Smaragd",
    "Drachenzahn",
    "Morbol-Samen",
    "W\xFCstenzahn",
    "Windkristall",
    "Schattenkugel",
    "Glutauge",
    "Teufelsspore",
    "Gigas-Robe",
    "Gryphon-Feder",
    "Zerberus-Zahn",
    "Nadel",
    "K\xE4" "ferpanzer",
    "F\xFChler",
    "Kr\xF6tenfett",
    "Sichel",
    "Oger-Zahn",
    "Chim\xE4ra-Horn",
    "Getreidesamen",
    "Quahls Haar",
    "Monti-Schnabel",
    "Cocka-Haut",
    "Geheimarznei",
    "Funkelstein",
    "Gigas-Kralle",
    "Zahnrad",
    "Rosenbl\xFCte",
    "Heilmittel",
    "Freia-B\xFCste",
    "D\xE4monenmaske",
    "Reserve 22",
    "Pflanzensamen",
    "Wundersamen",
    "Obstkern",
    "Obstkern",
    "Obstkern",
    "Gem\xFCsesamen",
    "Gem\xFCsesamen",
    "Gem\xFCsesamen",
    "Weizenkorn",
    "Halstuch",
    "Shellas Pass",
    "Kilanda-Stein",
    "Kaktusbl\xFCte",
    "Reserve 23",
    "Ultimanith",
    "Dunkelquarz",
    "Reserve 24",
    "Reserve 25",
    "Reserve 26",
    "Reserve 27",
    "Reserve 28",
    "Reserve 29",
    "Reserve 30",
    "Reserve 31",
    "Reserve 32",
    "Reserve 33",
    "Streifenapfel",
    "Klingelkirsche",
    "Bunttrauben",
    "Sternenm\xF6hre",
    "K\xFCrbiskartoff.",
    "Rundmais",
    "Fleisch",
    "Fisch",
    "Bauernbrot",
    "Wasser",
    "Milch",
    "Wunderwasser",
    "Feuersplitter",
    "Wassersplitter",
    "Donnersplitter",
    "Dunkelsplitter",
    "Weizenb\xFCndel",
    "Mehl",
    "???",
    "Item-Gil",
    "Anf\xE4ngerwaffe",
    "K\xE4mpferwaffe",
    "Heldenwaffe",
    "Brachial-Waffe",
    "Triumph-Waffe",
    "Meisterwaffe",
    "Legend\xE4rwaffe",
    "Heroenwaffe",
    "G\xF6tterwaffe",
    "Schattenwaffe",
    "Mondwaffe",
    "Bronzepanzer",
    "Eisenpanzer",
    "Mithril-Panzer",
    "Feuerpanzer",
    "Eispanzer",
    "Donnerpanzer",
    "Chrono-Panzer",
    "\xC4on-Panzer",
    "Sakral-Panzer",
    "Heiligenpanzer",
    "Goldpanzer",
    "Funkelpanzer",
    "Diamantpanzer",
    "Terra-Panzer",
    "Eisenplatte",
    "Mithril-Platte",
    "Feuerplatte",
    "Eisplatte",
    "Donnerplatte",
    "Heiligenplatte",
    "Diamantplatte",
    "Zauberplatte",
    "Legend\xE4rpl.",
    "Bronzef\xE4ustl.",
    "Eisenf\xE4ustling",
    "Mithril-F\xE4ustl.",
    "Feuerf\xE4ustling",
    "Eisf\xE4ustling",
    "Donnerf\xE4ustl.",
    "Goldf\xE4ustling",
    "Diamantf\xE4ustl.",
    "Bronzehaube",
    "Eisenhaube",
    "Mithril-Haube",
    "Feuerhaube",
    "Eishaube",
    "Donnerhaube",
    "Chrono-Haube",
    "\xC4on-Haube",
    "Diamanthaube",
    "Bronzeriemen",
    "Eisenriemen",
    "Mithril-Riemen",
    "Feuerriemen",
    "Eisriemen",
    "Donnerriemen",
    "Sakral-Riemen",
    "Orkanriemen",
    "Diamantriemen",
    "Feuernadel",
    "Eisnadel",
    "Donnernadel",
    "Zeitglocke",
    "Uhrwerk",
    "Weberei",
    "Spinnerei",
    "Goldschmiede",
    "Geheimbuch",
    "Geheimlehre",
    "Schmuckkoffer",
    "Langfinger",
    "Taschendieb",
    "Kleptomane",
    "B\xE4renst\xE4rke",
    "Dunkelreif",
    "Schattenreif",
    "Elfenreif",
    "Engelsreif",
    "Lichtreif",
    "Brillenmacher",
    "Optiker",
    "Mullbinde",
    "Muschelseide",
    "Objektiv",
    "Teleskop",
    "L\xF6wenseele",
    "Drachenseele",
    "Zauberbuch",
    "Schamanenbuch",
    "Tabu-Buch",
    "Ultimator",
    "Defendor",
    "Skizze 94",
    "Skizze 95",
    "Skizze 96",
    "Skizze 97",
    "Skizze 98",
    "Skizze 99",
    "Skizze 100",
};

char *gItemNames_It[] = {
    "DUMMY-IT",
    "Spada corta",
    "Spada ferrea",
    "Spada leggera",
    "Sciabola piuma",
    "Bastarda",
    "Difensore",
    "Lama runica",
    "Excalibur",
    "Lagunarock",
    "Sp. preziosa",
    "Spada paterna",
    "Spada Marr",
    "Test 1",
    "Test 2",
    "Spada Ultima ",
    "Equip. 116",
    "Equip. 117",
    "Lancia ferrea",
    "Partigiana",
    "Lancia sonica",
    "Lan. titanica",
    "Alabarda",
    "Highwind",
    "Lan. draconica",
    "Lan. dragone",
    "Gungnir",
    "Longinus",
    "Lan. preziosa",
    "Lan. paterna",
    "Lancia Marr",
    "Lancia Ultima",
    "Equip. 119",
    "Equip. 120",
    "Equip. 121",
    "Equip. 122",
    "Martello orco",
    "Ondamartello ",
    "Martello runico",
    "Martello goblin",
    "Martello sonico",
    "Prismartello ",
    "Martello mithril",
    "Mart. mistico",
    "Mart. prezioso",
    "Mart. paterno",
    "Martello Marr",
    "Martello Ultima",
    "Equip. 124",
    "Equip. 125",
    "Equip. 126",
    "Equip. 127",
    "Auracchetta",
    "Spaccatutto",
    "Duoracchetta",
    "Clava element.",
    "Clava acciaio",
    "Mazza prism.",
    "Punta farfalla",
    "Maglio regale",
    "Maglio magno",
    "Mag. prezioso",
    "Maglio paterno",
    "Maglio Marr",
    "Maglio Ultima",
    "Equip. 129",
    "Equip. 130",
    "Equip. 131",
    "Equip. 132",
    "Abiti viaggio",
    "Cotta bronzea",
    "Cotta ferrea",
    "Cotta mithril",
    "Cotta ardente",
    "Cotta glaciale",
    "Cot. tuonante",
    "Cot. temporale",
    "Cotta eterna",
    "Cot. benedetta",
    "Cotta santa",
    "Cotta dorata",
    "Cot. cristallina",
    "C. adamantina",
    "Cotta Gaia",
    "Arm. mistica",
    "Giubba zucca",
    "Giubba",
    "Giubba abbon.",
    "Scudo semplice",
    "Scudo ferreo",
    "Scudo mithril",
    "Scudo ardente",
    "Scudo glaciale",
    "Sc. tuonante",
    "Scudo santo",
    "S. adamantino",
    "Scudo runico",
    "Scudo chocobo",
    "Manopole",
    "Man. bronzee",
    "Man. ferree",
    "Man. mithril",
    "Man. ardenti",
    "Man. glaciali",
    "Man. tuonanti",
    "Man. dorate",
    "M. adamantine",
    "Elmo",
    "Elmo bronzeo",
    "Elmo ferreo",
    "Elmo mithril",
    "Elmo ardente",
    "Elmo glaciale",
    "Elmo tuonante",
    "Elmo temp.",
    "Elmo eterno",
    "Elmo adamant.",
    "Cin. semplice",
    "Cinta bronzea",
    "Cinta ferrea",
    "Cinta mithril",
    "Fas. ardente",
    "Fas. glaciale",
    "Fas. tuonante",
    "F. benedetta",
    "Fascia d'Icaro",
    "F. adamantina",
    "Simbolo Fuoco",
    "Simbolo Gelo",
    "Simbolo Tuono",
    "Orol. preciso",
    "Orol. perfetto",
    "Misanga blu",
    "Misan. bianca",
    "Collana d'oro",
    "Amuleto saggio",
    "Talism. saggio",
    "Brac. floreale",
    "Amuleto rapido",
    "Talism. rapido",
    "Emblema ladro",
    "Fascia eroica",
    "Or. demoniaco",
    "Orec. infernale",
    "Orec. spiritato",
    "Orec. angelico",
    "An. cristallino",
    "Occ. mendaci",
    "Lente mendace",
    "Fas. curativa",
    "Brac. di giada",
    "Lenti potere",
    "Lenti d'aquila",
    "Cuor di leone",
    "Cuor di drago",
    "Anima di mago",
    "Anima d'alfiere",
    "Anima element.",
    "Anello forza",
    "Shuriken",
    "Mangiauomini",
    "Ascia bipenne",
    "Ashura",
    "Nocche kaiser",
    "Lingua fuoco",
    "Brando gelum",
    "Dadi truccati",
    "Ammazzorchi",
    "Engetsurin",
    "Lama Sasuke",
    "Mjollnir",
    "Pantomima",
    "Amenomurakumo",
    "Masamune",
    "Gekkabijin",
    "Brando cipolla",
    "Polsino potere",
    "Berretto verde",
    "Zanna amuleto",
    "F. attorcigliat.",
    "Armil. pesante",
    "Guanto gigante",
    "Baffo drago",
    "Tritamago",
    "Asta runica",
    "Libro luce",
    "Asta saggia",
    "Incredibacch.",
    "Camp. runica",
    "Asta del mago",
    "Liuto di No\xE8",
    "Galatyn",
    "Tomo di Ultima",
    "Brac. argento",
    "Campana gatto",
    "Anello fatato",
    "Capp. d'Icaro",
    "Anello candito",
    "Kris",
    "Pantof. rosse",
    "Mater. oscura",
    "Forcina dorata",
    "Modello acuto",
    "Fiocco",
    "Spadino",
    "Trinciapollo",
    "SaveTheQueen",
    "Trapano",
    "Scudo piccolo",
    "Occh. argentei",
    "Brac. brillante",
    "Cappa nera",
    "Elmo alleato",
    "Mantello elfico",
    "Bracc. mistico",
    "An. protettivo",
    "Egida",
    "Coda di topo",
    "Orsetto",
    "Tasc. moguri",
    "Tasc. chocobo",
    "Tasc. goblin",
    "Super tascap.",
    "Anello Fire",
    "Anello Blizzard",
    "Anello Thunder",
    "Anello Energia",
    "Anello Reiz",
    "Ciond. terreno",
    "Ciond. lunare",
    "Ciond. stellare",
    "Ciond. solare",
    "Equip. 187",
    "Equip. 188",
    "Equip. 189",
    "Equip. 190",
    "Equip. 191",
    "Equip. 192",
    "Equip. 193",
    "Equip. 194",
    "Equip. 195",
    "Equip. 196",
    "Equip. 197",
    "Equip. 198",
    "Equip. 199",
    "Equip. 200",
    "Equip. 201",
    "Equip. 202",
    "Equip. 203",
    "Equip. 204",
    "Equip. 205",
    "Equip. 206",
    "Equip. 207",
    "Equip. 208",
    "Equip. 209",
    "Equip. 210",
    "Fire",
    "Blizzard",
    "Thunder",
    "???",
    "Slow",
    "Energia",
    "Esna",
    "Reiz",
    "Sancta",
    "Stop",
    "Antima",
    "Maledizione",
    "Malattia",
    "Circolo magico",
    "Ultima",
    "Vampa",
    "Meteora",
    "Oscurit\xE0",
    "Ardore",
    "Afferra",
    "Confusione",
    "Tornado",
    "Esamina",
    "Minaccia",
    "Preferiti",
    "Dadi",
    "Colpa",
    "Regola",
    "Tutti",
    "Ventaglio",
    "Circolo",
    "Traccia",
    "Potenziam.",
    "Doppio",
    "Aggiungi",
    "Rilascia",
    "Barriera",
    "Coda di fenice",
    "Bronzo",
    "Ferro",
    "Mithril",
    "Oricalco",
    "Diam. grezzo",
    "Oro",
    "Argento",
    "Pezzo bronzo",
    "Pezzo ferro",
    "Picc. cristallo",
    "Sfera cristallo",
    "Rubino",
    "Giada",
    "Lega",
    "Roccia lavica",
    "Gel rinfresc.",
    "Sfera di tuono",
    "Acqua santa",
    "Sabbia angel.",
    "Penna gialla",
    "Seta blu",
    "Seta bianca",
    "Unghia maligna",
    "Unghia demone",
    "Lacrime fata",
    "Lacrime angelo",
    "Spada antica",
    "Unc. maledetto",
    "Cinta d'orco",
    "Scaglia pesce",
    "Sfera verde",
    "Unghia drago",
    "Seme molboro",
    "Zanna desert.",
    "Cristallo aria",
    "Globo etereo",
    "Occhio rosso",
    "Sp. stregata",
    "Toga nobile",
    "Ala di grifone",
    "Zanna cerbero",
    "Ago",
    "Guscio duro",
    "Antenna verme",
    "Olio di rospo",
    "Falce seghett.",
    "Zanna babau",
    "Corno chimera",
    "Seme",
    "Baffo iaguaro",
    "Becco di zuu",
    "Sca. basilisco",
    "Pozione antica",
    "Framm. lucido",
    "Unghia giga",
    "Ingranaggio",
    "Fiore secco",
    "Panacea",
    "Stat. votiva",
    "M. demoniaca",
    "extra 22",
    "Seme floreale",
    "Seme strano",
    "Seme di frutto",
    "Seme di frutto",
    "Seme di frutto",
    "Seme vegetale",
    "Seme vegetale",
    "Seme vegetale",
    "Chicco grano",
    "Band. logora",
    "March. Shella",
    "Zolfo Kilanda",
    "Fiore cactus",
    "extra 23",
    "Ultimite",
    "Sfera oscura",
    "extra 24",
    "extra 25",
    "extra 26",
    "extra 27",
    "extra 28",
    "extra 29",
    "extra 30",
    "extra 31",
    "extra 32",
    "extra 33",
    "Mela rigata",
    "Cilieg. grumose",
    "Uva iridata",
    "Car. stellata",
    "Tuberozucca",
    "Grano rotondo",
    "Carne",
    "Pesce",
    "Pagnotta",
    "Acqua minerale",
    "Latte",
    "Liquido strano",
    "Framm. fuoco",
    "Framm. acqua",
    "Framm. tuono",
    "Framm. oscuro",
    "Grano",
    "Farina",
    "???",
    "Guil",
    "Arma semplice",
    "Arma guerr.",
    "Arma prode",
    "Arma potente",
    "Arma vittor.",
    "Arma esperta ",
    "Arma leggend.",
    "Arma eroica",
    "Arma celest.",
    "Arma oscura",
    "Arma lunare",
    "Arm. bronzea ",
    "Arm. ferrea",
    "Arm. mithril",
    "Arm. ardente",
    "Arm. glaciale",
    "Arm. tuonante",
    "Arm. temporale",
    "Arm. eterna",
    "Arm. pura",
    "Arm. sacra",
    "Arm. dorata",
    "Arm. di luce",
    "Arm. adamant.",
    "Arm. terrena",
    "Scudo ferreo",
    "Scudo mithril",
    "Scudo ardente",
    "Scudo glaciale",
    "Sc. tuonante",
    "Scudo sacro",
    "S. adamantino",
    "Scudo magico",
    "S. leggendario",
    "Man. bronzee",
    "Man. ferree",
    "Man. mithril",
    "Man. ardenti",
    "Man. glaciali",
    "Man. tuonanti",
    "Man. dorate",
    "M. adamantine",
    "Cel. bronzea",
    "Celata ferrea",
    "Celata mithril",
    "Cel. ardente",
    "Cel. glaciale",
    "Cel. tuonante",
    "Cel. temporale",
    "Celata eterna",
    "Cel. adamant.",
    "Cinta bronzea",
    "Cinta ferrea",
    "Cinta mithril",
    "Cinta ardente",
    "Cinta glaciale",
    "Cinta tuonante",
    "Cinta pura",
    "Cinta d'aria",
    "Cinta adaman.",
    "Arte ardente",
    "Arte glaciale",
    "Arte tuonante",
    "Meccanismo",
    "Meccan. nuovo",
    "Filo blu",
    "Filo bianco",
    "Arte dorata",
    "Tomo sagg.",
    "Segreti sagg.",
    "Acc. da donna",
    "Tomo velocit\xE0",
    "Segreti veloc.",
    "Brigantologia",
    "Corr. d'ardore",
    "Corr. folletto",
    "Corr. demon.",
    "Corr. fatato",
    "Corr. angelico",
    "Anello di luce",
    "Tec. ottiche",
    "Occ. firmati",
    "Corr. curativo",
    "Cor. alla moda",
    "Tec. oculist.",
    "Lenti firmate",
    "Anima di leone",
    "Anima di drago",
    "Tomo di magia",
    "Tomo stregon.",
    "Tomo proibito",
    "Arma invincib.",
    "An. invincibile",
    "Modello 94",
    "Modello 95",
    "Modello 96",
    "Modello 97",
    "Modello 98",
    "Modello 99",
    "Modello 100",
};

char *gItemNames_Fr[] = {
    "TEST-FR",
    "Rapi\xE8re",
    "Ep\xE9" "e de fer",
    "Glaive",
    "Sabre plume",
    "Ep\xE9" "e b\xE2tarde",
    "Vengeresse",
    "Ep\xE9" "e runique",
    "Excalibur",
    "Ragnarok",
    "Ep\xE9" "e pr\xE9" "cieuse",
    "Ep\xE9" "e de papa",
    "Ep\xE9" "e de Marr",
    "Test 1",
    "Test 2",
    "Ep\xE9" "e Ultima",
    "Equip. 116",
    "Equip. 117",
    "Lance de fer",
    "Pertuisane",
    "Lance sonique",
    "Lance de titan",
    "Hallebarde",
    "Hauvent",
    "Lance dragon",
    "Dragonite",
    "Gungnir",
    "Longinus",
    "Lance pr\xE9" "ci.",
    "Lance de papa",
    "Lance de Marr",
    "Lance Ultima",
    "Equip. 119",
    "Equip. 120",
    "Equip. 121",
    "Equip. 122",
    "Marteau d'orc",
    "Mart. \xE0 ondes",
    "Mart. runique",
    "Mart. gobelin",
    "Mart. sonique",
    "Mart. prisma.",
    "Plomm\xE9" "e",
    "Mart. mystiq.",
    "Mart. pr\xE9" "cieux",
    "Mart. de papa",
    "Mart. de Marr",
    "Mart. Ultima",
    "Equip. 124",
    "Equip. 125",
    "Equip. 126",
    "Equip. 127",
    "B\xE2ton d'aura",
    "Percuteur",
    "B\xE2ton rafales",
    "Gourdin \xE9l\xE9m.",
    "Gourdin de fer",
    "Gourd. prism.",
    "Squamule",
    "Crosse royale",
    "B\xE2ton m\xEAl\xE9" "e",
    "Massue pr\xE9" "ci.",
    "Massue papa",
    "Massue Marr",
    "Massue Ultima",
    "Equip. 129",
    "Equip. 130",
    "Equip. 131",
    "Equip. 132",
    "Habits voyage",
    "Cuir. bronze",
    "Haubert",
    "Cuir. mithril",
    "Cotte flamb.",
    "Cotte gel\xE9" "e",
    "Cotte orag.",
    "Cotte temps",
    "Cotte \xE9tern.",
    "Cotte b\xE9nite",
    "Cotte sainte",
    "Cotte d'or",
    "Cotte cristal",
    "Cuir. diamant",
    "Cuirasse Ga\xEF" "a",
    "Cuir. mystique",
    "Mant. patate",
    "Manteau",
    "Manteau grand",
    "Ecu",
    "Pavois de fer",
    "Pavois mithril",
    "Bouc. flamboy.",
    "Bouclier gel\xE9",
    "Bouc. orageux",
    "Targe sacr\xE9" "e",
    "Targe diamant",
    "Bouc. runique",
    "Bouc. chocobo",
    "Gantelets",
    "Manicles",
    "Gant. de fer",
    "Gant. mithril",
    "Brass. flamb.",
    "Brass. gel\xE9s",
    "Brass. orag.",
    "Gant. d'or",
    "Brass. diam.",
    "Morion",
    "Armet bronze",
    "Heaume",
    "Armet mithril",
    "Armet flamb.",
    "Armet gel\xE9",
    "Armet orageux",
    "Armet temps",
    "Armet \xE9ternel",
    "Armet diamant",
    "Vieille ceinture",
    "Ceint. bronze",
    "Ceint. fer",
    "Ceint. mithril",
    "Ceint. flamb.",
    "Ceinturon gel\xE9",
    "Ceint. orageux",
    "Obi",
    "Ceint. ail\xE9",
    "Ceint. diamant",
    "Insigne flam.",
    "Insigne neige",
    "Insigne \xE9" "clair",
    "Montre pr\xE9" "c.",
    "Montre infaill.",
    "Misanga bleu",
    "Misanga blanc",
    "Collier d'or",
    "Amulet. sage",
    "Talism. sage",
    "Broche fleurie",
    "Amul. v\xE9locit\xE9",
    "Tali. v\xE9locit\xE9",
    "Embl\xE8me voleur",
    "Bandeau z\xE8le",
    "Boucle d\xE9mon.",
    "Boucle diabo.",
    "Boucle f\xE9\xE9riq.",
    "Boucle ang\xE9l.",
    "Bague cristal",
    "Lunettes tord.",
    "Verres tordus",
    "Band. gu\xE9riss.",
    "Poignet jade",
    "Lunet. puiss.",
    "Lunet. d'aigle",
    "C\x9Cur de lion",
    "C\x9Cur de drag.",
    "Ame de sorc.",
    "Ame d'\xE9v\xEAque",
    "Ame \xE9l\xE9ment.",
    "Bague vigueur",
    "Shuriken",
    "Cannibale",
    "Double harken",
    "Ashura",
    "C\xE9sariffe",
    "Langue de feu",
    "Ep\xE9" "e de glace",
    "D\xE9 pip\xE9",
    "Hachoir",
    "Faucheuse",
    "Lame Sasuke",
    "Mjollnir",
    "Mascarade",
    "Murasame",
    "Masamune",
    "Freya",
    "Lame oignon",
    "Forcelet",
    "B\xE9ret vert",
    "Amulette mor.",
    "Turban",
    "Brass. lourd",
    "Gant de g\xE9" "ant",
    "Moust. dragon",
    "Bro. de mages",
    "Sceptre runiq.",
    "Livre lumi\xE8re",
    "Sceptre sage",
    "Sceptre merv.",
    "Cloche runique",
    "Magekane",
    "Luth de Noah",
    "Galatyn",
    "Tome d'Ultima",
    "Poignet d'arg.",
    "Clochette chat",
    "Bague f\xE9\xE9riq.",
    "Chapeau ail\xE9",
    "Bague bonbon",
    "Kris",
    "Chauss. roug.",
    "H-Espace",
    "Epingle d'or",
    "Motif taotie",
    "Ruban",
    "Main gauche",
    "C. \xE0 volaille",
    "Save Queen",
    "Perceuse",
    "Pelta",
    "Lunettes arg.",
    "Poignet \xE9tin.",
    "Cagoule noire",
    "Armet d'Ara\xEF",
    "Cape elfique",
    "Anneau merv.",
    "Bague protec.",
    "A\xE9gis",
    "Queue de rat",
    "Ours peluche",
    "Poche de mog",
    "Poche chocobo",
    "Poche gobelin",
    "Poche ultime",
    "Bague Brasier",
    "Bague Glacier",
    "Bague Foudre",
    "Bague Soin",
    "Bague Vie",
    "Pend. terre",
    "Pend. lune",
    "Pend. \xE9toile",
    "Pend. soleil",
    "Equip. 187",
    "Equip. 188",
    "Equip. 189",
    "Equip. 190",
    "Equip. 191",
    "Equip. 192",
    "Equip. 193",
    "Equip. 194",
    "Equip. 195",
    "Equip. 196",
    "Equip. 197",
    "Equip. 198",
    "Equip. 199",
    "Equip. 200",
    "Equip. 201",
    "Equip. 202",
    "Equip. 203",
    "Equip. 204",
    "Equip. 205",
    "Equip. 206",
    "Equip. 207",
    "Equip. 208",
    "Equip. 209",
    "Equip. 210",
    "Brasier",
    "Glacier",
    "Foudre",
    "???",
    "Somni",
    "Soin",
    "Esuna",
    "Vie",
    "Sid\xE9ral",
    "Stop",
    "Gravit\xE9",
    "Mal\xE9" "fice",
    "Maladie",
    "Cercle magique",
    "Ultima",
    "Atomnium",
    "M\xE9t\xE9ore",
    "Obscurit\xE9",
    "Z\xE8le",
    "Ramasser",
    "Folie",
    "Tourbillon",
    "Examiner",
    "Menacer",
    "Pr\xE9" "f\xE9r\xE9s",
    "D\xE9" "couper",
    "R\xE9primander",
    "Commander",
    "Tout",
    "Fan",
    "Encercler",
    "Suivre",
    "Am\xE9liorer",
    "Double",
    "Ajouter",
    "Lib\xE9rer",
    "Barri\xE8re",
    "Queue ph\xE9nix",
    "Bronze",
    "Fer",
    "Mithril",
    "Orichalque",
    "Diamant",
    "Or",
    "Argent",
    "Ecl. de bronze",
    "Eclat de fer",
    "Petit cristal",
    "Boule cristal",
    "Rubis",
    "Jade",
    "Alliage",
    "Roc magma",
    "Gel rafra\xEE" "ch.",
    "Sph\xE8re foudre",
    "Eau b\xE9nite",
    "Souffle d'ange",
    "Plume jaune",
    "Soie bleue",
    "Soie blanche",
    "Griffe galkim.",
    "Griffe d\xE9mon.",
    "Larme de f\xE9" "e",
    "Larme d'ange",
    "Ep\xE9" "e ancienne",
    "Crosse maud.",
    "Ceinture d'orc",
    "Ecail. poisson",
    "Sph\xE8re verte",
    "Croc dragon",
    "Graine xylomid",
    "Croc d\xE9sert",
    "Crist. de vent",
    "Orbe au-del\xE0",
    "\x8Cil rouge",
    "Spore m\xE9phit.",
    "Robe seigneur",
    "Aile de griffon",
    "Croc cerb\xE8re",
    "Epine",
    "Carapace",
    "Antenne ver",
    "Huile crapaud",
    "Faux \xE9" "br\xE9" "ch\xE9" "e",
    "Croc d'ogre",
    "Corne chimaira",
    "Graine",
    "Mous. coeurl",
    "Bec de zu",
    "Ecaille gallus",
    "Pot. ancienne",
    "Eclat brillant",
    "Griffe gigas",
    "Tige",
    "Fleur \xE9" "cras\xE9" "e",
    "Rem\xE8" "de",
    "Stat. d\xE9" "esse",
    "Masque d\xE9mon.",
    "Extra 22",
    "Graine fleur",
    "Graine \xE9tran.",
    "Graine fruit",
    "Graine fruit",
    "Graine fruit",
    "Graine l\xE9gume",
    "Graine l\xE9gume",
    "Graine l\xE9gume",
    "Graine de bl\xE9",
    "Bandana us\xE9",
    "Marque Shella",
    "Soufre Kilanda",
    "Fleur cactus",
    "Extra 23",
    "Ultimite",
    "Sph\xE8re obsc.",
    "Extra 24",
    "Extra 25",
    "Extra 26",
    "Extra 27",
    "Extra 28",
    "Extra 29",
    "Extra 30",
    "Extra 31",
    "Extra 32",
    "Extra 33",
    "Pomme ray\xE9" "e",
    "Cerises",
    "Raisin color\xE9",
    "Carotte \xE9toil.",
    "Patate courge",
    "Epi de ma\xEFs",
    "Viande",
    "Poisson",
    "Pain de camp.",
    "Eau min\xE9rale",
    "Lait",
    "Liquide \xE9tran.",
    "Eclat de Feu",
    "Eclat d'Eau",
    "Eclat de Tonn.",
    "Eclat d'Obscu.",
    "Gerbe de bl\xE9",
    "Farine",
    "???",
    "Gils",
    "Arme d\xE9" "butant",
    "Arme guerrier",
    "Arme vaillante",
    "Arme puiss.",
    "Arme victor.",
    "Arme d'expert",
    "Arme l\xE9gend.",
    "Arme de h\xE9ros",
    "Arme c\xE9leste",
    "Arme obscure",
    "Arme lunaire",
    "Armure bronze",
    "Armure de fer",
    "Armure mithril",
    "Armure de feu",
    "Armure glace",
    "Armure tonner.",
    "Armure temps",
    "Armure \xE9tern.",
    "Armure pure",
    "Armure sainte",
    "Armure d'or",
    "Armure lumi\xE8re",
    "Armure diam.",
    "Armure terre",
    "Bouclier fer",
    "Bouclier mith.",
    "Bouclier feu",
    "Bouclier glace",
    "Bouclier tonn.",
    "Bouclier saint",
    "Bouclier diam.",
    "Bouclier magi.",
    "Bouclier l\xE9g.",
    "Gants bronze",
    "Gants de fer",
    "Gants mithril",
    "Brass. de feu",
    "Brass. glace",
    "Brass. tonn.",
    "Gants d'or",
    "Gants diamant",
    "Casque bronze",
    "Casque de fer",
    "Casque mithril",
    "Casque de feu",
    "Casque glace",
    "Casque tonn.",
    "Casque temps",
    "Casque d'\xE9ter.",
    "Casque diam.",
    "Ceinture bro.",
    "Ceinture fer",
    "Ceinture mith.",
    "Ceinture feu",
    "Ceinture glace",
    "Ceinture tonn.",
    "Ceinture pure",
    "Ceinture vent",
    "Ceinture diam.",
    "Art. de feu",
    "Art. de glace",
    "Art. de tonn.",
    "Rouage 1",
    "Rouage 2",
    "Fil bleu",
    "Fil blanc",
    "Artifice d'or",
    "Tome sagesse",
    "Secr. sagesse",
    "Access. f\xE9m.",
    "Tome v\xE9locit\xE9",
    "Secr. v\xE9locit\xE9",
    "Brigandologie",
    "Kit de z\xE8le",
    "Kit de galkim.",
    "Kit d\xE9moniaq.",
    "Kit f\xE9\xE9rique",
    "Kit ang\xE9lique",
    "Bague lumi\xE8re",
    "Livre de lunet.",
    "Lunettes marq.",
    "Kit de soin",
    "Kit de mode",
    "Livre de verr.",
    "Verres marque",
    "Ame de lion",
    "Ame de dragon",
    "Tome de magie",
    "Tome sorcell.",
    "Tome interdit",
    "Arme formid.",
    "Bague d'invin.",
    "Sch\xE9ma 94",
    "Sch\xE9ma 95",
    "Sch\xE9ma 96",
    "Sch\xE9ma 97",
    "Sch\xE9ma 98",
    "Sch\xE9ma 99",
    "Sch\xE9ma 100",
};

char *gItemNames_Es[] = {
    "DUMMY-SP",
    "Espad. cobre",
    "Espad. hierro",
    "Espad. pr\xE1" "ct.",
    "Sable plumas",
    "Espad. bastar.",
    "Defensor",
    "Guada\xF1" "a runa",
    "Excalibur",
    "Ragnarok",
    "Espad. codic.",
    "Espad. pater.",
    "Espada Marro",
    "Prueba 1",
    "Prueba 2",
    "Espada Artema",
    "Equipo 116",
    "Equipo 117",
    "Javal. hierro",
    "Guerrillera",
    "Javal. s\xF3nica",
    "Javal. tit\xE1n",
    "Alabarda",
    "Sed venganza",
    "Javal. drag\xF3n",
    "Lanz. drgonia.",
    "Gungnir",
    "Longinus",
    "Lanza codic.",
    "Lanza paterna",
    "Lanza Marro",
    "Javal. Artema",
    "Equipo 119",
    "Equipo 120",
    "Equipo 121",
    "Equipo 122",
    "Martillo orco",
    "Martillo onda",
    "Martillo runa",
    "Mart. duende",
    "Martillo s\xF3nic.",
    "Mart. prisma",
    "Martillo mitril.",
    "Mart. m\xEDstic.",
    "Mart. codic.",
    "Martill. pater.",
    "Martillo Marro",
    "Mart. Artema",
    "Equipo 124",
    "Equipo 125",
    "Equipo 126",
    "Equipo 127",
    "Raqueta aura",
    "Raqueta dura",
    "Disparad. dual",
    "Estaca elem.",
    "Estaca acero",
    "Garrot. prisma",
    "Cabeza marip.",
    "Tal\xF3n reina",
    "Gran cachipo.",
    "Cachip. tesor.",
    "Cachip. pater.",
    "Cachip. Marr.",
    "Cachip. Artem.",
    "Equipo 129",
    "Equipo 130",
    "Equipo 131",
    "Equipo 132",
    "Ropa de viaje",
    "Plaq. bronce",
    "Plaq. hierro",
    "Plaq. mitrilo",
    "Coraza feroz",
    "Coraza congel.",
    "Coraza torm.",
    "Coraza tiempo",
    "Coraza eterna",
    "Coraza bendita",
    "Coraza santo",
    "Coraza de oro",
    "Coraza cristal",
    "Plaq. diam.",
    "Plaqu\xEDn gaia",
    "Armad. m\xEDst.",
    "Abrig. calab.",
    "Abrigo",
    "Abrig. extrag.",
    "Escud. improv.",
    "Escudo hierro",
    "Escudo mitrilo",
    "Escudo feroz",
    "Escud. congel.",
    "Escud. tormen.",
    "Escudo santo",
    "Escud. diam.",
    "Escudo runa",
    "Escud. chocob.",
    "Guanteletes",
    "Guant. bronce",
    "Guant. hierro",
    "Guant. mitrilo",
    "Pulser. fuego",
    "Pulser. glac.",
    "Pulser. el\xE9" "c.",
    "Pulser. oro",
    "Pulser. diam.",
    "Yelmo",
    "Yelmo bronce",
    "Yelmo hierro",
    "Yelmo mitril.",
    "Yelmo feroz",
    "Yelmo congel.",
    "Yelmo tormen.",
    "Yelmo tiempo",
    "Yelmo eterno",
    "Yelmo diam.",
    "Cintur. antig.",
    "Cintur. bron.",
    "Cintur. hierr.",
    "Cintur. mitril.",
    "Faja feroz",
    "Faja congel.",
    "Faja tormenta",
    "Faja bendita",
    "Cintur. alad.",
    "Cintur. diam.",
    "Insig. Llam.",
    "Insig. Escar.",
    "Insig. Rayo",
    "Reloj preciso",
    "Reloj decidido",
    "Misanga azul",
    "Misanga blanca",
    "Collar de oro",
    "Amulet. sabid.",
    "Talis. sabio",
    "Brazal de flor",
    "Amuleto veloz",
    "Talis. veloz",
    "Emblem. ladr\xF3n",
    "Cint. entusias.",
    "Arete demonio",
    "Arete diablo",
    "Arete hada",
    "Arete \xE1ngel",
    "Anillo cristal",
    "Gafas torcidas",
    "Alcance torc.",
    "Cinta sanad.",
    "Brazal de jade",
    "Anteoj. poder",
    "Anteoj. \xE1guil.",
    "Coraz. le\xF3n",
    "Coraz. drag.",
    "Alma druida",
    "Alma obispo",
    "Alma elemental",
    "Anillo fuerza",
    "Pu\xF1" "al",
    "Maneater",
    "Doble harken",
    "Ashura",
    "Mit\xF3n kaiser",
    "Sable ardiente",
    "Marca de hielo",
    "Dados cargad.",
    "Mataogros",
    "Engetsurin",
    "Hoja Sasuke",
    "Miolnir",
    "Mascarada",
    "Amenomurakumo",
    "Masamune",
    "Gekkabijin",
    "Espad. ceboll.",
    "Mu\xF1" "eq. Poder",
    "Boina verde",
    "Amulet. colm.",
    "Campanilla",
    "Brzlet. pesad.",
    "Guante gigante",
    "Patilla drag.",
    "Moledor mago",
    "Vara de runa",
    "Libro de luz",
    "Vara cham\xE1n",
    "Vara prodig.",
    "Timbre de runa",
    "Vara de mago",
    "Luto de Noah",
    "Galatyn",
    "Tomo Artema",
    "Brazal plata",
    "Timbre gato",
    "Anillo hada",
    "Gorra alas",
    "Anillo dulce",
    "Kris",
    "Chancl. roj.",
    "Materia negra",
    "Horquilla oro",
    "Modelo claro",
    "Cinta",
    "Mano izquierda",
    "Cuchillo pollo",
    "Salvar Reina",
    "Taladro",
    "Escudete",
    "Gafas plata",
    "Brazal cent.",
    "Capucha negra",
    "Yelmo aliado",
    "Capa elven",
    "Aro maravilla",
    "Anill. protec.",
    "\xC9gida",
    "Cola de rata",
    "Osito peluche",
    "Bolsillo moguri",
    "Bolsi. chocob.",
    "Bolsillo gobi",
    "Bolsill. esen.",
    "Anillo Fuego",
    "Anillo Hielo",
    "Anillo Electro",
    "Anillo de Cura",
    "Anillo de Vida",
    "Colg. tierra",
    "Colgante luna",
    "Colg. estre.",
    "Colgante sol",
    "Equipo 187",
    "Equipo 188",
    "Equipo 189",
    "Equipo 190",
    "Equipo 191",
    "Equipo 192",
    "Equipo 193",
    "Equipo 194",
    "Equipo 195",
    "Equipo 196",
    "Equipo 197",
    "Equipo 198",
    "Equipo 199",
    "Equipo 200",
    "Equipo 201",
    "Equipo 202",
    "Equipo 203",
    "Equipo 204",
    "Equipo 205",
    "Equipo 206",
    "Equipo 207",
    "Equipo 208",
    "Equipo 209",
    "Equipo 210",
    "Piro",
    "Hielo",
    "Electro",
    "\xBF\xBF??",
    "Freno",
    "Cura",
    "Esuna",
    "L\xE1zaro",
    "Sanctus",
    "Paro",
    "Gravedad",
    "Maldici\xF3n",
    "Enfermedad",
    "C\xEDrc. m\xE1gic.",
    "Artema",
    "Fulgor",
    "Meteo",
    "Ceguera ",
    "Entusiasmo",
    "Capturar",
    "Confundir",
    "Remolino",
    "Examinar",
    "Amenazar",
    "Favoritos",
    "Dados",
    "Culpar",
    "Gobernar",
    "Todos",
    "Abanico",
    "C\xEDrculo",
    "Arrastrar",
    "Mejorar",
    "Doble",
    "Agregar",
    "Liberar",
    "Barrera",
    "Cola f\xE9nix",
    "Bronce",
    "Hierro",
    "Mitrilo",
    "Orichalcum",
    "Diam. miner.",
    "Oro",
    "Plata",
    "Casco bronce",
    "Casco acero",
    "Cristal dimin.",
    "Bola cristal",
    "Rub\xED",
    "Jade",
    "Aleaci\xF3n",
    "Roca magma",
    "Gel fr\xEDo",
    "Bal\xF3n el\xE9" "c.",
    "Agua sagrada",
    "Arena \xE1ngel",
    "Pluma amarilla",
    "Seda azul",
    "Seda blanca",
    "Garra diablillo",
    "Garra diablo",
    "L\xE1grim. hada",
    "L\xE1grim. \xE1ngel",
    "Espad. antigua",
    "Ganch. maldito",
    "Cintur. orco",
    "Escama pez",
    "Esfera verde",
    "Colmillo drag.",
    "Semilla molbol",
    "Colmill. desier.",
    "Cristal viento",
    "Globo et\xE9reo",
    "Ojo rojo",
    "Espora m\xE1gica",
    "T\xFAnica poder",
    "Ala de grifo",
    "Colmill. cerber.",
    "Picadura",
    "Escudo duro",
    "Anten. gusan.",
    "Aceite rana",
    "Guad\xF1" "a. dent.",
    "Colmillo ogro",
    "Cuern. quime.",
    "Semilla ",
    "Patilla bengal",
    "Pico de zu",
    "Escam. cocat.",
    "Poci\xF3n antig.",
    "Casco brillante",
    "Garra gigas",
    "Equipamiento",
    "Flor aplastada",
    "Remedio",
    "Estatui. diosa",
    "M\xE1sc. diab\xF3l.",
    "Extra 22",
    "Semilla de flor",
    "Sem. extra\xF1" "a",
    "Semilla frutal",
    "Semilla frutal",
    "Semilla frutal",
    "Semilla vegetal",
    "Semilla vegetal",
    "Semilla vegetal",
    "Semilla trigo",
    "Bandana gast.",
    "Marca Sulena",
    "Sulfur. Kiland.",
    "Flor de cactus",
    "Extra 23",
    "Ultimita",
    "Esfera oscura",
    "Extra 24",
    "Extra 25",
    "Extra 26",
    "Extra 27",
    "Extra 28",
    "Extra 29",
    "Extra 30",
    "Extra 31",
    "Extra 32",
    "Extra 33",
    "Manzan. rayad.",
    "Racim. cerez.",
    "Uvas arcoiris",
    "Zanah. estre.",
    "Calabaza",
    "Ma\xEDz redondo",
    "Carne",
    "Pescado",
    "Pan",
    "Agua",
    "Leche",
    "L\xEDq. extra\xF1o",
    "Frag. de fuego",
    "Frag. de agua",
    "Frag. el\xE9" "ctrico",
    "Frag. oscuro",
    "Trigo",
    "Harina",
    "\xBF\xBF??",
    "Guiles",
    "Arma novato",
    "Arma guerrero",
    "Arma valiant",
    "Gran arma",
    "Arma victor.",
    "Arma maestra",
    "Arma legend.",
    "Arma h\xE9roe",
    "Arma celestial",
    "Arma oscura",
    "Arma lunar",
    "Armadur. bron.",
    "Armadur. hie.",
    "Armadur. mit.",
    "Armad. fuego",
    "Armadur. glac.",
    "Armadur. el\xE9" "c.",
    "Armadur. tiem.",
    "Armadur. eter.",
    "Armadura pura",
    "Armadur. sag.",
    "Armadura oro",
    "Armadura luz",
    "Armadur. dia.",
    "Armadur. tie.",
    "Escudo hierro",
    "Escudo mitril.",
    "Escudo fuego",
    "Escudo glacial",
    "Escudo el\xE9" "c.",
    "Escud. sagrad.",
    "Escud. diam.",
    "Escudo m\xE1g.",
    "Escud. legen.",
    "Guantes bron.",
    "Guantes hie.",
    "Guantes mit.",
    "Guantes fuego",
    "Guantes glac.",
    "Guantes el\xE9" "c.",
    "Guantes oro",
    "Guantes diam.",
    "Morri\xF3n bro.",
    "Morri\xF3n hie.",
    "Morri\xF3n mit.",
    "Morri\xF3n fue.",
    "Morri\xF3n gla.",
    "Morri\xF3n el\xE9" "c.",
    "Morri\xF3n tie.",
    "Morri\xF3n eter.",
    "Morri\xF3n dia.",
    "Cintur. bron.",
    "Cintur. hie.",
    "Cintur. mit.",
    "Cintur. fue.",
    "Cintur. glac.",
    "Cintur. el\xE9" "c.",
    "Cintur. puro",
    "Cintur. vient.",
    "Cintur. diam.",
    "Artesan. fueg.",
    "Artesan. glac.",
    "Artesan. el\xE9" "c.",
    "Cronos",
    "Nuevo cronos",
    "Hilo azul",
    "Hilo blanco",
    "Artesan. oro",
    "Tomo sabid.",
    "Secre. sabio",
    "Acces. dama",
    "Tomo veloc.",
    "Secre. veloc.",
    "Bandidolog\xED" "a",
    "Equip. entusia.",
    "Equip. diablill.",
    "Equip. demon.",
    "Equip. hada",
    "Equip. \xE1ngel",
    "Anillo de luz",
    "T\xE9" "cn. \xF3ptica",
    "Lentes dise\xF1.",
    "Equipo remedio",
    "Equipo moda",
    "T\xE9" "cn. asombr.",
    "Gafas dise\xF1.",
    "Alma le\xF3n",
    "Alma drag\xF3n",
    "Tomo de magia",
    "Tomo hechicer.",
    "Tomo prohib.",
    "Arma grande",
    "Anillo invenc.",
    "Dise\xF1o 94",
    "Dise\xF1o 95",
    "Dise\xF1o 96",
    "Dise\xF1o 97",
    "Dise\xF1o 98",
    "Dise\xF1o 99",
    "Dise\xF1o 100",
};

const u8 gItemIcons[] = {
    52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    52, 52, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    52, 52, 52, 52, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    52, 52, 52, 52, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 52, 52, 52, 52, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 15,
    15, 15, 15, 15, 14, 14, 14, 14, 52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
    16, 16, 16, 16, 52, 17, 17, 17, 52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 28, 18, 18, 18, 18, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
    52, 52, 52, 9, 9, 9, 9, 9, 9, 9, 9, 9, 52, 52, 52, 52,
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 20, 21, 22,
    23, 24, 25, 26, 27, 51, 19, 19, 19, 52, 52, 52, 52, 49, 50, 52,
    52, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
    48, 48, 48, 48, 48,
};
