//
// Generated By: dol2asm
// Translation Unit: MetroTRK/Portable/nubinit
//

#include "TRK_MINNOW_DOLPHIN/MetroTRK/Portable/nubinit.h"
#include "TRK_MINNOW_DOLPHIN/MetroTRK/Portable/serpoll.h"
#include "TRK_MINNOW_DOLPHIN/MetroTRK/Portable/MWTrace.h"

/* 8044D8B8-8044D8C0 07A5D8 0004+04 1/1 4/4 0/0 .bss             gTRKBigEndian */
BOOL gTRKBigEndian;

/*
 * --INFO--
 * PAL Address: 0x801A9370
 * PAL Size: 332b
 * EN Address: 0x801A8254
 * EN Size: 332b
 * JP Address: 0x801A3898
 * JP Size: 312b
 */
DSError TRKInitializeNub(void) {
    int ret;
    DSError uartErr;

    ret = TRKInitializeEndian();

#ifndef VERSION_GCCJGC
    MWTRACE(1, "Initialize NUB\n");
#endif
    if (ret == DS_NoError) {
        usr_put_initialize();
    }
    if (ret == DS_NoError) {
        ret = TRKInitializeEventQueue();
    }
    if (ret == DS_NoError) {
        ret = TRKInitializeMessageBuffers();
    }
    if (ret == DS_NoError) {
        ret = TRKInitializeDispatcher();
    }
    InitializeProgramEndTrap();
#ifndef VERSION_GCCJGC
    if (ret == DS_NoError) {
        ret = TRKInitializeSerialHandler();
    }
    if (ret == DS_NoError) {
        ret = TRKInitializeTarget();
    }
#endif
    if (ret == DS_NoError) {
        uartErr = TRKInitializeIntDrivenUART(0x0000e100, 1, 0, &gTRKInputPendingPtr);
        TRKTargetSetInputPendingPtr(gTRKInputPendingPtr);
        if (uartErr != DS_NoError) {
            ret = uartErr;
        }
    }
#ifdef VERSION_GCCJGC
    if (ret == DS_NoError) {
        ret = TRKInitializeSerialHandler();
    }
    if (ret == DS_NoError) {
        ret = TRKInitializeTarget();
    }
#endif
    return ret;
}

/*
 * --INFO--
 * PAL Address: 0x801A934C
 * PAL Size: 36b
 * EN Address: 0x801A8230
 * EN Size: 36b
 * JP Address: 0x801A3874
 * JP Size: 36b
 */
DSError TRKTerminateNub(void) {
    TRKTerminateSerialHandler();
    return DS_NoError;
}

/*
 * --INFO--
 * PAL Address: 0x801A9324
 * PAL Size: 40b
 * EN Address: 0x801A8208
 * EN Size: 40b
 * JP Address: 0x801A384C
 * JP Size: 40b
 */
void TRKNubWelcome(void) {
#ifdef VERSION_GCCJGC
    TRK_board_display("MetroTRK for GAMECUBE v2.0");
#else
    TRK_board_display("MetroTRK for GAMECUBE v2.6");
#endif
    return;
}

BOOL TRKInitializeEndian(void) {
    u8 bendian[4];
    BOOL result = FALSE;
    gTRKBigEndian = TRUE;

    bendian[0] = 0x12;
    bendian[1] = 0x34;
    bendian[2] = 0x56;
    bendian[3] = 0x78;

    if (*(u32*)bendian == 0x12345678) {
        gTRKBigEndian = TRUE;
    } else if (*(u32*)bendian == 0x78563412) {
        gTRKBigEndian = FALSE;
    } else {
        result = TRUE;
    }
    return result;
}