// Function: Create__8CPartMngFv
// Entry: 8005f0fc
// Size: 1308 bytes

/* WARNING: Struct "CGBaseObj": ignoring overlapping field "vtable" */

void Create__8CPartMngFv(CPartMng *partMng)

{
  float fVar1;
  float fVar2;
  float fVar3;
  CPartMng *pCVar4;
  int iVar5;
  
  C_MTXPerspective(FLOAT_8032fe8c,FLOAT_8032fe90,FLOAT_8032fe94,FLOAT_8032fe58,
                   (Mtx *)&ppvScreenMatrix);
  PSMTX44Copy(&ppvScreenMatrix,&ppvScreenMatrix0);
  memset(partMng->unkBuffer,0,0x108);
  partMng->m_usbEdit[0x1a] = '\0';
  partMng->m_usbEdit[0x19] = '\0';
  partMng->m_usbEdit[0x18] = '\0';
  DAT_8032ed68 = 1;
  DAT_8032ed6c = 0;
  DAT_8032ed70 = 0;
  DAT_8032ed74 = 0;
  if (Game.game.m_currentSceneId == 7) {
    pppCreateHeap__FP9_pppEnvStUl(&partMng->m_pppEnvSt,0x100000);
  }
  else {
    pppCreateHeap__FP9_pppEnvStUl(&partMng->m_pppEnvSt,0xc0000);
  }
  pppEnvStPtr = &partMng->m_pppEnvSt;
  DAT_8032ed7c = 0;
  PSMTXIdentity(&ppvUnitMatrix);
  ppvZeroVector.z = FLOAT_8032fe5c;
  ppvZeroVector.y = FLOAT_8032fe5c;
  ppvZeroVector.x = FLOAT_8032fe5c;
  DAT_8032ed78 = 0;
  DAT_8032ed79 = 0;
  PSMTXIdentity(&ppvWorldMatrix);
  PSMTXIdentity(&ppvWorldMatrix);
  PSMTXIdentity(&ppvCameraMatrix0);
  PSMTXCopy(&ppvCameraMatrix0,&ppvCameraMatrix0);
  partMng->m_materialSet = (CMaterialSet *)0x0;
  partMng->m_textureSet = (CTextureSet *)0x0;
  partMng->m_pppModelStArr = (pppModelSt *)0x0;
  partMng->m_usbEdit[0] = '\0';
  partMng->m_usbEdit[1] = '\0';
  partMng->m_usbEdit[2] = '\0';
  partMng->m_usbEdit[3] = '\0';
  iVar5 = 4;
  pCVar4 = partMng;
  do {
    pCVar4->m_unk0x1d4_0x3d3[0] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[1] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[2] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[3] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[4] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[5] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[6] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[7] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[8] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[9] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[10] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0xb] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0xc] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0xd] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0xe] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0xf] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x10] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x11] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x12] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x13] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x14] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x15] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x16] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x17] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x18] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x19] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x1a] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x1b] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x1c] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x1d] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x1e] = (void *)0x0;
    pCVar4->m_unk0x1d4_0x3d3[0x1f] = (void *)0x0;
    pCVar4 = (CPartMng *)(pCVar4->m_editCameraExtra + 0x10);
    iVar5 = iVar5 + -1;
  } while (iVar5 != 0);
  iVar5 = 4;
  pCVar4 = partMng;
  do {
    pCVar4->m_streamTextRaw[0] = (void *)0x0;
    pCVar4->m_streamTextRaw[1] = (void *)0x0;
    pCVar4->m_streamTextRaw[2] = (void *)0x0;
    pCVar4->m_streamTextRaw[3] = (void *)0x0;
    pCVar4->m_streamTextRaw[4] = (void *)0x0;
    pCVar4->m_streamTextRaw[5] = (void *)0x0;
    pCVar4->m_streamTextRaw[6] = (void *)0x0;
    pCVar4->m_streamTextRaw[7] = (void *)0x0;
    pCVar4->m_streamTextRaw[8] = (void *)0x0;
    pCVar4->m_streamTextRaw[9] = (void *)0x0;
    pCVar4->m_streamTextRaw[10] = (void *)0x0;
    pCVar4->m_streamTextRaw[0xb] = (void *)0x0;
    pCVar4->m_streamTextRaw[0xc] = (void *)0x0;
    pCVar4->m_streamTextRaw[0xd] = (void *)0x0;
    pCVar4->m_streamTextRaw[0xe] = (void *)0x0;
    pCVar4->m_streamTextRaw[0xf] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x10] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x11] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x12] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x13] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x14] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x15] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x16] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x17] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x18] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x19] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x1a] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x1b] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x1c] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x1d] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x1e] = (void *)0x0;
    pCVar4->m_streamTextRaw[0x1f] = (void *)0x0;
    pCVar4 = (CPartMng *)(pCVar4->m_editCameraExtra + 0x10);
    iVar5 = iVar5 + -1;
  } while (iVar5 != 0);
  iVar5 = 4;
  pCVar4 = partMng;
  do {
    pCVar4->m_pppProgOffsetReconstructionTable[0] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[1] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[2] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[3] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[4] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[5] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[6] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[7] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[8] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[9] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[10] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0xb] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0xc] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0xd] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0xe] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0xf] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x10] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x11] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x12] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x13] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x14] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x15] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x16] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x17] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x18] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x19] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x1a] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x1b] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x1c] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x1d] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x1e] = (long *)0x0;
    pCVar4->m_pppProgOffsetReconstructionTable[0x1f] = (long *)0x0;
    pCVar4 = (CPartMng *)(pCVar4->m_editCameraExtra + 0x10);
    iVar5 = iVar5 + -1;
  } while (iVar5 != 0);
  iVar5 = 0x40;
  pCVar4 = partMng;
  do {
    pCVar4->m_pppMngStArr[0].m_baseTime = -0x1000;
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectHandle = -1;
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectSlot = -1;
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectStopFlag = '\0';
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectKind = '\x01';
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectStartFrame = 0;
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectStartedOnce = '\0';
    pCVar4->m_pppMngStArr[0].m_soundEffectData.m_soundEffectFadeFrames = 0x1e;
    pCVar4->m_pppMngStArr[1].m_baseTime = -0x1000;
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectHandle = -1;
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectSlot = -1;
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectStopFlag = '\0';
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectKind = '\x01';
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectStartFrame = 0;
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectStartedOnce = '\0';
    pCVar4->m_pppMngStArr[1].m_soundEffectData.m_soundEffectFadeFrames = 0x1e;
    pCVar4->m_pppMngStArr[2].m_baseTime = -0x1000;
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectHandle = -1;
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectSlot = -1;
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectStopFlag = '\0';
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectKind = '\x01';
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectStartFrame = 0;
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectStartedOnce = '\0';
    pCVar4->m_pppMngStArr[2].m_soundEffectData.m_soundEffectFadeFrames = 0x1e;
    pCVar4->m_pppMngStArr[3].m_baseTime = -0x1000;
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectHandle = -1;
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectSlot = -1;
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectStopFlag = '\0';
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectKind = '\x01';
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectStartFrame = 0;
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectStartedOnce = '\0';
    pCVar4->m_pppMngStArr[3].m_soundEffectData.m_soundEffectFadeFrames = 0x1e;
    pCVar4->m_pppMngStArr[4].m_baseTime = -0x1000;
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectHandle = -1;
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectSlot = -1;
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectStopFlag = '\0';
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectKind = '\x01';
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectStartFrame = 0;
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectStartedOnce = '\0';
    pCVar4->m_pppMngStArr[4].m_soundEffectData.m_soundEffectFadeFrames = 0x1e;
    pCVar4->m_pppMngStArr[5].m_baseTime = -0x1000;
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectHandle = -1;
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectSlot = -1;
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectStopFlag = '\0';
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectKind = '\x01';
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectStartFrame = 0;
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectStartedOnce = '\0';
    pCVar4->m_pppMngStArr[5].m_soundEffectData.m_soundEffectFadeFrames = 0x1e;
    pCVar4 = (CPartMng *)(pCVar4->m_usbEdit + 0x20);
    iVar5 = iVar5 + -1;
  } while (iVar5 != 0);
  partMng->m_pdtSlots[0].m_pppDataHead = (_pppDataHead *)0x0;
  fVar1 = FLOAT_8032fe5c;
  partMng->m_pdtSlots[1].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[2].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[3].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[4].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[5].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[6].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[7].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[8].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[9].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[10].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0xb].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0xc].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0xd].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0xe].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0xf].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x10].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x11].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x12].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x13].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x14].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x15].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x16].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x17].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x18].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x19].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x1a].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x1b].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x1c].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x1d].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x1e].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_pdtSlots[0x1f].m_pppDataHead = (_pppDataHead *)0x0;
  partMng->m_recvBuff = (void *)0x0;
  partMng->m_usbEdit[4] = '\0';
  partMng->m_usbEdit[5] = '\0';
  partMng->m_usbEdit[6] = '\0';
  partMng->m_usbEdit[7] = '\0';
  partMng->m_usbEdit[8] = '\0';
  partMng->m_usbEdit[9] = '\0';
  partMng->m_usbEdit[10] = '\0';
  partMng->m_usbEdit[0xb] = '\0';
  partMng->m_usbEdit[0xc] = '\0';
  partMng->m_usbEdit[0xd] = '\0';
  partMng->m_usbEdit[0xe] = '\0';
  partMng->m_usbEdit[0xf] = '\0';
  (partMng->m_pppEnvSt).m_envParam = fVar1;
  (partMng->m_pppEnvSt).m_mngStCount = 0x10;
  (partMng->m_pppEnvSt).m_isEditMode = 1;
  partMng->m_usbEdit[0x1c] = '\0';
  partMng->m_usbEdit[0x1d] = '\0';
  partMng->m_usbEdit[0x1e] = '\0';
  partMng->m_usbEdit[0x1f] = '\0';
  memset(partMng->unkBuffer,0,0x108);
  fVar1 = FLOAT_8032fe9c;
  (partMng->m_pppEnvSt).m_boxMinX = FLOAT_8032fe98;
  fVar2 = FLOAT_8032fea0;
  (partMng->m_pppEnvSt).m_boxMaxX = fVar1;
  fVar3 = FLOAT_8032fea4;
  (partMng->m_pppEnvSt).m_boxMinY = fVar2;
  fVar2 = FLOAT_8032fea8;
  (partMng->m_pppEnvSt).m_boxMaxY = fVar3;
  (partMng->m_pppEnvSt).m_boxMinZ = fVar1;
  (partMng->m_pppEnvSt).m_boxMaxZ = fVar2;
  return;
}

