// Function: onCreate__8CGObjectFv
// Entry: 80081ea4
// Size: 980 bytes

/* WARNING: Struct "CGBaseObj": ignoring overlapping field "vtable" */

void onCreate__8CGObjectFv(CGObject *gObject)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  float fVar5;
  float fVar6;
  float fVar7;
  float fVar8;
  int8_t *piVar9;
  int iVar10;
  int iVar11;
  
  fVar6 = FLOAT_80330418;
  fVar4 = FLOAT_80330390;
  fVar2 = FLOAT_80330350;
  (gObject->m_worldPosition).z = FLOAT_80330350;
  fVar1 = FLOAT_80330338;
  (gObject->m_worldPosition).y = fVar2;
  fVar5 = FLOAT_803303d4;
  (gObject->m_worldPosition).x = fVar2;
  fVar3 = FLOAT_80330360;
  (gObject->m_groundHitOffset).z = fVar2;
  fVar7 = FLOAT_80330434;
  (gObject->m_groundHitOffset).y = fVar2;
  fVar8 = FLOAT_80330438;
  (gObject->m_groundHitOffset).x = fVar2;
  gObject->m_rotBaseZ = fVar2;
  gObject->m_rotBaseY = fVar2;
  gObject->m_rotBaseX = fVar2;
  gObject->m_rotTargetZ = fVar2;
  gObject->m_rotTargetY = fVar2;
  gObject->m_rotTargetX = fVar2;
  (gObject->m_bodyOffset).x = fVar2;
  (gObject->m_bodyOffset).y = fVar4;
  (gObject->m_bodyOffset).z = fVar2;
  (gObject->m_jumpOffset).x = fVar2;
  (gObject->m_jumpOffset).y = fVar6;
  (gObject->m_jumpOffset).z = fVar2;
  (gObject->m_moveOffset).x = fVar2;
  (gObject->m_moveOffset).y = fVar1;
  (gObject->m_moveOffset).z = fVar2;
  gObject->m_charaModelHandle = (CCharaPcsCHandle *)0x0;
  gObject->m_weaponModelHandle = (CCharaPcsCHandle *)0x0;
  gObject->m_shieldModelHandle = (CCharaPcsCHandle *)0x0;
  gObject->m_animStateMisc = 0xff;
  *(byte *)((int)&gObject->m_weaponNodeFlags + 1) =
       *(byte *)((int)&gObject->m_weaponNodeFlags + 1) & 0x7f;
  *(byte *)((int)&gObject->m_weaponNodeFlags + 1) =
       *(byte *)((int)&gObject->m_weaponNodeFlags + 1) & 0xbf | 0x40;
  gObject->m_moveBaseSpeed = fVar5;
  gObject->m_currentAnimSlot = -1;
  gObject->m_bodyEllipsoidRadius = fVar3;
  gObject->m_bodyEllipsoidOffset = fVar2;
  gObject->m_bodyEllipsoidAspect = fVar1;
  gObject->m_capsuleHalfHeight = fVar3;
  gObject->m_attackColRadius = fVar7;
  gObject->m_bodyColRadius = fVar8;
  gObject->m_nearColRadius = fVar6;
  gObject->m_bgColMask = 0;
  *(byte *)((int)&gObject->m_weaponNodeFlags + 1) =
       *(byte *)((int)&gObject->m_weaponNodeFlags + 1) & 0xdf;
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0xef | 0x10;
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0xf7;
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0xfb | 4;
  gObject->m_objectFlags = 1;
  gObject->m_displayFlags = 3;
  gObject->m_rotationX = fVar1;
  gObject->m_rotationY = fVar1;
  gObject->m_rotationZ = fVar1;
  gObject->m_attrFlags = 0;
  gObject->m_ownerType = -1;
  gObject->m_classWorkIndex = '\0';
  gObject->m_scriptHandle = (void **)0x0;
  fVar3 = FLOAT_8033043c;
  gObject->unk_0x184 = fVar2;
  gObject->unk_0x188 = fVar2;
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0xfe;
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0xdf | 0x20;
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0xbf;
  (gObject->m_moveVec).x = -NAN;
  gObject->m_animSlotSel = -1;
  gObject->m_turnSpeed = fVar2;
  gObject->m_pushParamB = '\0';
  gObject->m_pushParamA = '\0';
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0xbf;
  gObject->m_frontHitAngle = fVar3;
  gObject->m_lookAtTarget = (CGObject *)0x0;
  gObject->m_stepSlopeLimit = fVar1;
  gObject->m_lookAtTimer = fVar1;
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0xdf;
  gObject->m_animBlend = fVar1;
  gObject->m_bgAttrValue = fVar1;
  gObject->m_bounceFactor = fVar1;
  gObject->m_gravityY = fVar2;
  gObject->m_jumpLandingDampening = fVar2;
  gObject->m_stateFlags0 = gObject->m_stateFlags0 & 0xef;
  (gObject->m_bgCollisionQuat).z = fVar2;
  (gObject->m_bgCollisionQuat).y = fVar2;
  (gObject->m_bgCollisionQuat).x = fVar2;
  (gObject->m_bgCollisionQuat).w = fVar1;
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0xef;
  gObject->m_dispItemTimer = '\0';
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0x7f;
  *(float *)gObject->m_lastBgAttr = fVar1;
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0xf7;
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0xfb;
  gObject->m_collisionPushTimerMax = 0x32;
  (gObject->m_radiusCtrl).x = 0.0;
  *(undefined *)&gObject->m_lastBgGroup = 0;
  gObject->m_moveAnimState = '\0';
  gObject->m_moveAnimSubState = '\0';
  gObject->m_randSeedLo = '\0';
  gObject->m_randSeedHi = '\0';
  gObject->m_stateFlags0 = gObject->m_stateFlags0 & 0xf7;
  gObject->m_ownerSlot = '\0';
  gObject->m_stateFlags0 = gObject->m_stateFlags0 & 0x7f;
  (gObject->m_radiusCtrlVel).x = fVar2;
  (gObject->m_radiusCtrl).y = fVar2;
  (gObject->m_radiusCtrl).z = fVar1;
  fVar3 = FLOAT_80330440;
  fVar1 = FLOAT_8033036c;
  iVar10 = 0;
  (gObject->m_radiusCtrlVel).y = (gObject->m_radiusCtrl).y;
  (gObject->m_radiusCtrlVel).z = (gObject->m_radiusCtrl).z;
  gObject->m_groundFriction = (gObject->m_radiusCtrlVel).x;
  (gObject->m_hitNormal).x = fVar1;
  gObject->m_bgDownDist = fVar3;
  gObject->m_moveMode = '\0';
  gObject->m_moveModePrevious = '\x04';
  gObject->m_groundSlide = fVar2;
  (gObject->m_hitNormal).z = fVar2;
  (gObject->m_hitNormal).y = fVar2;
  gObject->m_worldParam = fVar2;
  gObject->m_lookAtTargetNodeIndex = -1;
  gObject->m_worldParamA = 0.0;
  gObject->m_lookAtAccumYaw = fVar2;
  gObject->m_lookAtAccumPitch = fVar2;
  gObject->m_weaponAttachNode = -1;
  gObject->m_shieldAttachNodeIndex = -1;
  gObject->m_lastMapIdHit = '\0';
  gObject->m_lastMapIdExtra = '\0';
  *(byte *)&gObject->m_weaponNodeFlags = *(byte *)&gObject->m_weaponNodeFlags & 0x7f;
  (gObject->m_extraMoveVec).z = fVar2;
  (gObject->m_extraMoveVec).y = fVar2;
  (gObject->m_extraMoveVec).x = fVar2;
  *(byte *)&gObject->m_shieldNodeFlags = *(byte *)&gObject->m_shieldNodeFlags & 0xfe;
  gObject->field_0x56 = 0x7d;
  *(float *)gObject->m_worldMode = fVar2;
  iVar11 = 2;
  do {
    piVar9 = gObject->m_animQueue + iVar10 + -0x41;
    *piVar9 = -1;
    piVar9[1] = -1;
    piVar9[2] = -1;
    piVar9[3] = -1;
    piVar9[4] = 0xff;
    piVar9[5] = -1;
    piVar9[6] = -1;
    piVar9[7] = 0xff;
    piVar9 = gObject->m_animQueue + iVar10 + -0x39;
    *piVar9 = -1;
    piVar9[1] = -1;
    piVar9[2] = -1;
    piVar9[3] = -1;
    piVar9[4] = 0xff;
    piVar9[5] = -1;
    piVar9[6] = -1;
    piVar9[7] = 0xff;
    piVar9 = gObject->m_animQueue + iVar10 + -0x31;
    *piVar9 = -1;
    piVar9[1] = -1;
    piVar9[2] = -1;
    piVar9[3] = -1;
    piVar9[4] = 0xff;
    piVar9[5] = -1;
    piVar9[6] = -1;
    piVar9[7] = 0xff;
    piVar9 = gObject->m_animQueue + iVar10 + -0x29;
    iVar10 = iVar10 + 0x20;
    *piVar9 = -1;
    piVar9[1] = -1;
    piVar9[2] = -1;
    piVar9[3] = -1;
    piVar9[4] = 0xff;
    piVar9[5] = -1;
    piVar9[6] = -1;
    piVar9[7] = 0xff;
    iVar11 = iVar11 + -1;
  } while (iVar11 != 0);
  memset(&gObject->m_attackColliders[0].m_localStart.y,0,0x180);
  memset(&gObject->m_damageColliders[0].m_localPosition.y,0,0x140);
  memset(gObject->m_dropItemCodes,0,8);
  return;
}

