"""Build rules for the GBA multiboot programs sent to linked Game Boy Advances.

Each program is split into per-unit assembly (gba/tools/split.py), reassembled,
linked, and checked against the retail image. The target objects are added to
objdiff.json so the programs count toward the version's progress report.
"""

import importlib.util
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import ninja_syntax
from .project import ProgressCategory, ProjectConfig

GBA_DIR = Path("gba")

# Programs per game version: category id -> program info.
PROGRAMS: Dict[str, Dict[str, Dict[str, str]]] = {
    "GCCP01": {
        "gba_cli": {
            "config": "cli",
            "name": "GBA Client",
            "disc_path": "dvd/gba/ffcc_cli.bin",
            "sha1": "ec0579f21b9211f2fec4d17fe5943f23309c5f4c",
        },
        "gba_mgr": {
            "config": "mgr",
            "name": "GBA Minigame",
            "disc_path": "dvd/minigame/mgr/mgr00.bin",
            "sha1": "6ef574cc6ae34e8a05bccb1a28f78e833fde58fa",
        },
    },
}

DISC_IMAGES = {"GCCP01": "FFCC_PAL.iso"}
ASFLAGS = "-mcpu=arm7tdmi -mthumb-interwork"


def _units(config_dir: Path) -> List[str]:
    text = (config_dir / "splits.txt").read_text(encoding="utf-8")
    return list(dict.fromkeys(re.findall(r"^(\S+):\s*$", text, re.M)))


def _path(path: Any) -> str:
    return str(path).replace(os.sep, "/")


def configure_gba(config: ProjectConfig, binutils_dir: Optional[Path]) -> None:
    programs = PROGRAMS.get(config.version)
    if not programs:
        return
    if importlib.util.find_spec("capstone") is None:
        print(
            "Warning: Python package 'capstone' not found; GBA programs are excluded "
            "from the build and progress report (pip install capstone)",
            file=sys.stderr,
        )
        return

    exe = ".exe" if sys.platform == "win32" else ""
    build = config.build_dir / config.version / "gba"
    orig = Path("orig") / config.version / "gba"
    tools = GBA_DIR / "tools"
    if binutils_dir is not None:
        prefix = binutils_dir / "arm-none-eabi-"
        binutils_stamp: List[str] = []
    else:
        prefix = config.build_dir / "tools" / "gba-binutils" / "bin" / "arm-none-eabi-"
        binutils_stamp = [_path(config.build_dir / "tools" / "gba-binutils" / ".version")]
    prefix_str = os.path.normpath(prefix)

    ninja_path = build / "build.ninja"
    ninja_path.parent.mkdir(parents=True, exist_ok=True)
    with open(ninja_path, "w", encoding="utf-8") as f:
        n = ninja_syntax.Writer(f)
        n.comment("GBA multiboot programs (generated by tools/gba_project.py)")
        n.variable("gba_asflags", ASFLAGS)
        n.newline()
        n.rule("gba_binutils", f"$python {_path(tools / 'download_binutils.py')} $outdir",
               description="TOOL $out")
        n.rule("gba_extract", f"$python {_path(tools / 'extract.py')} $in $outdir $paths",
               description="EXTRACT $out")
        n.rule("gba_split",
               f"$python {_path(tools / 'split.py')} $bin $config --asm-dir $asmdir "
               "--ldscript $ldscript --object-dir $objdir",
               description="SPLIT $config")
        n.rule("gba_as", f"{prefix_str}as{exe} $gba_asflags -o $out $in", description="AS $out")
        n.rule("gba_ld", f"{prefix_str}ld{exe} -T $ldscript -o $out --no-warn-rwx-segments -Map $map",
               description="LINK $out")
        n.rule("gba_objcopy", f"{prefix_str}objcopy{exe} -O binary -j .text -j .rodata $in $out",
               description="OBJCOPY $out")
        n.rule("gba_sha1", f"$python {_path(tools / 'check_sha1.py')} $in $sha1 $out",
               description="CHECK $in")
        n.newline()

        if binutils_stamp:
            n.build(binutils_stamp, "gba_binutils", implicit=_path(tools / "download_binutils.py"),
                    variables={"outdir": _path(Path(binutils_stamp[0]).parent)})

        bins = {cat: orig / Path(info["disc_path"]).name for cat, info in programs.items()}
        if not all(b.is_file() for b in bins.values()):
            n.build([_path(b) for b in bins.values()], "gba_extract",
                    _path(Path("orig") / config.version / DISC_IMAGES[config.version]),
                    implicit=_path(tools / "extract.py"),
                    variables={"outdir": _path(orig),
                               "paths": " ".join(info["disc_path"] for info in programs.values())})
        n.newline()

        split_deps = [_path(tools / "split.py"), _path(tools / "gbaanalysis.py")]
        for category, info in programs.items():
            config_dir = GBA_DIR / "config" / info["config"]
            out = build / info["config"]
            units = _units(config_dir)
            asm = [_path(out / "asm" / f"{u}.s") for u in units]
            ldscript = _path(out / "ldscript.ld")
            n.build(asm + [ldscript], "gba_split", _path(bins[category]),
                    implicit=split_deps + [_path(config_dir / "symbols.txt"), _path(config_dir / "splits.txt")],
                    variables={"bin": _path(bins[category]), "config": _path(config_dir),
                               "asmdir": _path(out / "asm"), "ldscript": ldscript,
                               "objdir": _path(out / "obj")})
            objects = []
            for unit in units:
                obj = _path(out / "obj" / f"{unit}.o")
                n.build(obj, "gba_as", _path(out / "asm" / f"{unit}.s"), implicit=binutils_stamp)
                objects.append(obj)
                config.extra_objdiff_units.append({
                    "name": f"gba/{info['config']}/{unit}",
                    "target_path": obj,
                    "metadata": {
                        "complete": False,
                        "progress_categories": [category],
                        "auto_generated": True,
                    },
                })
            elf = _path(out / f"{info['config']}.elf")
            n.build(elf, "gba_ld", implicit=objects + [ldscript],
                    variables={"ldscript": ldscript, "map": _path(out / f"{info['config']}.map")})
            image = _path(out / bins[category].name)
            n.build(image, "gba_objcopy", elf)
            ok = _path(out / "ok")
            n.build(ok, "gba_sha1", image, implicit=_path(tools / "check_sha1.py"),
                    variables={"sha1": info["sha1"]})
            n.newline()

            config.extra_source_inputs += objects + [ok]
            config.progress_categories.append(ProgressCategory(category, info["name"]))
            config.reconfig_deps = (config.reconfig_deps or []) + [config_dir / "splits.txt"]

    config.subninjas.append(ninja_path)
    config.reconfig_deps = (config.reconfig_deps or []) + [Path(__file__)]
